#!/usr/bin/env python3

import connexion

import os

from openapi_server import encoder
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func

def main():

    basedir = os.path.abspath(os.path.dirname(__file__))

    app = connexion.App(__name__, specification_dir='./openapi/')
    flaskapp = app.app # Flask(__name__)

    app.app.json_encoder = encoder.JSONEncoder
    app.add_api('openapi.yaml',
                arguments={'title': 'Provisioning MnS'},
                pythonic_params=True)
    flaskapp.config.from_mapping(
        SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'database.db')
    )

    db = SQLAlchemy(flaskapp)

    app.run(port=8080)


if __name__ == '__main__':
    main()
