# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.assurance_goal_single_all_of_attributes import AssuranceGoalSingleAllOfAttributes
from openapi_server import util

from openapi_server.models.assurance_goal_single_all_of_attributes import AssuranceGoalSingleAllOfAttributes  # noqa: E501

class AssuranceGoalSingleAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attributes=None):  # noqa: E501
        """AssuranceGoalSingleAllOf - a model defined in OpenAPI

        :param attributes: The attributes of this AssuranceGoalSingleAllOf.  # noqa: E501
        :type attributes: AssuranceGoalSingleAllOfAttributes
        """
        self.openapi_types = {
            'attributes': AssuranceGoalSingleAllOfAttributes
        }

        self.attribute_map = {
            'attributes': 'attributes'
        }

        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'AssuranceGoalSingleAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssuranceGoal_Single_allOf of this AssuranceGoalSingleAllOf.  # noqa: E501
        :rtype: AssuranceGoalSingleAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attributes(self):
        """Gets the attributes of this AssuranceGoalSingleAllOf.


        :return: The attributes of this AssuranceGoalSingleAllOf.
        :rtype: AssuranceGoalSingleAllOfAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this AssuranceGoalSingleAllOf.


        :param attributes: The attributes of this AssuranceGoalSingleAllOf.
        :type attributes: AssuranceGoalSingleAllOfAttributes
        """

        self._attributes = attributes
