# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CellIndividualOffset(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, rsrp_offset_ssb=None, rsrq_offset_ssb=None, sinr_offset_ssb=None, rsrp_offset_csi_rs=None, rsrq_offset_csi_rs=None, sinr_offset_csi_rs=None):  # noqa: E501
        """CellIndividualOffset - a model defined in OpenAPI

        :param rsrp_offset_ssb: The rsrp_offset_ssb of this CellIndividualOffset.  # noqa: E501
        :type rsrp_offset_ssb: int
        :param rsrq_offset_ssb: The rsrq_offset_ssb of this CellIndividualOffset.  # noqa: E501
        :type rsrq_offset_ssb: int
        :param sinr_offset_ssb: The sinr_offset_ssb of this CellIndividualOffset.  # noqa: E501
        :type sinr_offset_ssb: int
        :param rsrp_offset_csi_rs: The rsrp_offset_csi_rs of this CellIndividualOffset.  # noqa: E501
        :type rsrp_offset_csi_rs: int
        :param rsrq_offset_csi_rs: The rsrq_offset_csi_rs of this CellIndividualOffset.  # noqa: E501
        :type rsrq_offset_csi_rs: int
        :param sinr_offset_csi_rs: The sinr_offset_csi_rs of this CellIndividualOffset.  # noqa: E501
        :type sinr_offset_csi_rs: int
        """
        self.openapi_types = {
            'rsrp_offset_ssb': int,
            'rsrq_offset_ssb': int,
            'sinr_offset_ssb': int,
            'rsrp_offset_csi_rs': int,
            'rsrq_offset_csi_rs': int,
            'sinr_offset_csi_rs': int
        }

        self.attribute_map = {
            'rsrp_offset_ssb': 'rsrpOffsetSSB',
            'rsrq_offset_ssb': 'rsrqOffsetSSB',
            'sinr_offset_ssb': 'sinrOffsetSSB',
            'rsrp_offset_csi_rs': 'rsrpOffsetCSI-RS',
            'rsrq_offset_csi_rs': 'rsrqOffsetCSI-RS',
            'sinr_offset_csi_rs': 'sinrOffsetCSI-RS'
        }

        self._rsrp_offset_ssb = rsrp_offset_ssb
        self._rsrq_offset_ssb = rsrq_offset_ssb
        self._sinr_offset_ssb = sinr_offset_ssb
        self._rsrp_offset_csi_rs = rsrp_offset_csi_rs
        self._rsrq_offset_csi_rs = rsrq_offset_csi_rs
        self._sinr_offset_csi_rs = sinr_offset_csi_rs

    @classmethod
    def from_dict(cls, dikt) -> 'CellIndividualOffset':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CellIndividualOffset of this CellIndividualOffset.  # noqa: E501
        :rtype: CellIndividualOffset
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rsrp_offset_ssb(self):
        """Gets the rsrp_offset_ssb of this CellIndividualOffset.


        :return: The rsrp_offset_ssb of this CellIndividualOffset.
        :rtype: int
        """
        return self._rsrp_offset_ssb

    @rsrp_offset_ssb.setter
    def rsrp_offset_ssb(self, rsrp_offset_ssb):
        """Sets the rsrp_offset_ssb of this CellIndividualOffset.


        :param rsrp_offset_ssb: The rsrp_offset_ssb of this CellIndividualOffset.
        :type rsrp_offset_ssb: int
        """

        self._rsrp_offset_ssb = rsrp_offset_ssb

    @property
    def rsrq_offset_ssb(self):
        """Gets the rsrq_offset_ssb of this CellIndividualOffset.


        :return: The rsrq_offset_ssb of this CellIndividualOffset.
        :rtype: int
        """
        return self._rsrq_offset_ssb

    @rsrq_offset_ssb.setter
    def rsrq_offset_ssb(self, rsrq_offset_ssb):
        """Sets the rsrq_offset_ssb of this CellIndividualOffset.


        :param rsrq_offset_ssb: The rsrq_offset_ssb of this CellIndividualOffset.
        :type rsrq_offset_ssb: int
        """

        self._rsrq_offset_ssb = rsrq_offset_ssb

    @property
    def sinr_offset_ssb(self):
        """Gets the sinr_offset_ssb of this CellIndividualOffset.


        :return: The sinr_offset_ssb of this CellIndividualOffset.
        :rtype: int
        """
        return self._sinr_offset_ssb

    @sinr_offset_ssb.setter
    def sinr_offset_ssb(self, sinr_offset_ssb):
        """Sets the sinr_offset_ssb of this CellIndividualOffset.


        :param sinr_offset_ssb: The sinr_offset_ssb of this CellIndividualOffset.
        :type sinr_offset_ssb: int
        """

        self._sinr_offset_ssb = sinr_offset_ssb

    @property
    def rsrp_offset_csi_rs(self):
        """Gets the rsrp_offset_csi_rs of this CellIndividualOffset.


        :return: The rsrp_offset_csi_rs of this CellIndividualOffset.
        :rtype: int
        """
        return self._rsrp_offset_csi_rs

    @rsrp_offset_csi_rs.setter
    def rsrp_offset_csi_rs(self, rsrp_offset_csi_rs):
        """Sets the rsrp_offset_csi_rs of this CellIndividualOffset.


        :param rsrp_offset_csi_rs: The rsrp_offset_csi_rs of this CellIndividualOffset.
        :type rsrp_offset_csi_rs: int
        """

        self._rsrp_offset_csi_rs = rsrp_offset_csi_rs

    @property
    def rsrq_offset_csi_rs(self):
        """Gets the rsrq_offset_csi_rs of this CellIndividualOffset.


        :return: The rsrq_offset_csi_rs of this CellIndividualOffset.
        :rtype: int
        """
        return self._rsrq_offset_csi_rs

    @rsrq_offset_csi_rs.setter
    def rsrq_offset_csi_rs(self, rsrq_offset_csi_rs):
        """Sets the rsrq_offset_csi_rs of this CellIndividualOffset.


        :param rsrq_offset_csi_rs: The rsrq_offset_csi_rs of this CellIndividualOffset.
        :type rsrq_offset_csi_rs: int
        """

        self._rsrq_offset_csi_rs = rsrq_offset_csi_rs

    @property
    def sinr_offset_csi_rs(self):
        """Gets the sinr_offset_csi_rs of this CellIndividualOffset.


        :return: The sinr_offset_csi_rs of this CellIndividualOffset.
        :rtype: int
        """
        return self._sinr_offset_csi_rs

    @sinr_offset_csi_rs.setter
    def sinr_offset_csi_rs(self, sinr_offset_csi_rs):
        """Sets the sinr_offset_csi_rs of this CellIndividualOffset.


        :param sinr_offset_csi_rs: The sinr_offset_csi_rs of this CellIndividualOffset.
        :type sinr_offset_csi_rs: int
        """

        self._sinr_offset_csi_rs = sinr_offset_csi_rs
