# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CommModelType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DIRECT_COMMUNICATION_WO_NRF = "DIRECT_COMMUNICATION_WO_NRF"
    DIRECT_COMMUNICATION_WITH_NRF = "DIRECT_COMMUNICATION_WITH_NRF"
    INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY = "INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY"
    INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY = "INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY"
    def __init__(self):  # noqa: E501
        """CommModelType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CommModelType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommModelType of this CommModelType.  # noqa: E501
        :rtype: CommModelType
        """
        return util.deserialize_model(dikt, cls)
