# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CorrelatedNotification1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, source_object_instance=None, notification_ids=None):  # noqa: E501
        """CorrelatedNotification1 - a model defined in OpenAPI

        :param source_object_instance: The source_object_instance of this CorrelatedNotification1.  # noqa: E501
        :type source_object_instance: str
        :param notification_ids: The notification_ids of this CorrelatedNotification1.  # noqa: E501
        :type notification_ids: List[int]
        """
        self.openapi_types = {
            'source_object_instance': str,
            'notification_ids': List[int]
        }

        self.attribute_map = {
            'source_object_instance': 'sourceObjectInstance',
            'notification_ids': 'notificationIds'
        }

        self._source_object_instance = source_object_instance
        self._notification_ids = notification_ids

    @classmethod
    def from_dict(cls, dikt) -> 'CorrelatedNotification1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CorrelatedNotification_1 of this CorrelatedNotification1.  # noqa: E501
        :rtype: CorrelatedNotification1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_object_instance(self):
        """Gets the source_object_instance of this CorrelatedNotification1.


        :return: The source_object_instance of this CorrelatedNotification1.
        :rtype: str
        """
        return self._source_object_instance

    @source_object_instance.setter
    def source_object_instance(self, source_object_instance):
        """Sets the source_object_instance of this CorrelatedNotification1.


        :param source_object_instance: The source_object_instance of this CorrelatedNotification1.
        :type source_object_instance: str
        """
        if source_object_instance is None:
            raise ValueError("Invalid value for `source_object_instance`, must not be `None`")  # noqa: E501

        self._source_object_instance = source_object_instance

    @property
    def notification_ids(self):
        """Gets the notification_ids of this CorrelatedNotification1.


        :return: The notification_ids of this CorrelatedNotification1.
        :rtype: List[int]
        """
        return self._notification_ids

    @notification_ids.setter
    def notification_ids(self, notification_ids):
        """Sets the notification_ids of this CorrelatedNotification1.


        :param notification_ids: The notification_ids of this CorrelatedNotification1.
        :type notification_ids: List[int]
        """
        if notification_ids is None:
            raise ValueError("Invalid value for `notification_ids`, must not be `None`")  # noqa: E501

        self._notification_ids = notification_ids
