# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.ep_npc4_single import EPNpc4Single
from openapi_server.models.ep_npc6_single import EPNpc6Single
from openapi_server.models.ep_npc7_single import EPNpc7Single
from openapi_server.models.ep_npc8_single import EPNpc8Single
from openapi_server import util

from openapi_server.models.ep_npc4_single import EPNpc4Single  # noqa: E501
from openapi_server.models.ep_npc6_single import EPNpc6Single  # noqa: E501
from openapi_server.models.ep_npc7_single import EPNpc7Single  # noqa: E501
from openapi_server.models.ep_npc8_single import EPNpc8Single  # noqa: E501

class DDNMFFunctionSingleAllOf1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ep_npc4=None, ep_npc6=None, ep_npc7=None, ep_npc8=None):  # noqa: E501
        """DDNMFFunctionSingleAllOf1 - a model defined in OpenAPI

        :param ep_npc4: The ep_npc4 of this DDNMFFunctionSingleAllOf1.  # noqa: E501
        :type ep_npc4: List[EPNpc4Single]
        :param ep_npc6: The ep_npc6 of this DDNMFFunctionSingleAllOf1.  # noqa: E501
        :type ep_npc6: List[EPNpc6Single]
        :param ep_npc7: The ep_npc7 of this DDNMFFunctionSingleAllOf1.  # noqa: E501
        :type ep_npc7: List[EPNpc7Single]
        :param ep_npc8: The ep_npc8 of this DDNMFFunctionSingleAllOf1.  # noqa: E501
        :type ep_npc8: List[EPNpc8Single]
        """
        self.openapi_types = {
            'ep_npc4': List[EPNpc4Single],
            'ep_npc6': List[EPNpc6Single],
            'ep_npc7': List[EPNpc7Single],
            'ep_npc8': List[EPNpc8Single]
        }

        self.attribute_map = {
            'ep_npc4': 'EP_Npc4',
            'ep_npc6': 'EP_Npc6',
            'ep_npc7': 'EP_Npc7',
            'ep_npc8': 'EP_Npc8'
        }

        self._ep_npc4 = ep_npc4
        self._ep_npc6 = ep_npc6
        self._ep_npc7 = ep_npc7
        self._ep_npc8 = ep_npc8

    @classmethod
    def from_dict(cls, dikt) -> 'DDNMFFunctionSingleAllOf1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DDNMFFunction_Single_allOf_1 of this DDNMFFunctionSingleAllOf1.  # noqa: E501
        :rtype: DDNMFFunctionSingleAllOf1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ep_npc4(self):
        """Gets the ep_npc4 of this DDNMFFunctionSingleAllOf1.


        :return: The ep_npc4 of this DDNMFFunctionSingleAllOf1.
        :rtype: List[EPNpc4Single]
        """
        return self._ep_npc4

    @ep_npc4.setter
    def ep_npc4(self, ep_npc4):
        """Sets the ep_npc4 of this DDNMFFunctionSingleAllOf1.


        :param ep_npc4: The ep_npc4 of this DDNMFFunctionSingleAllOf1.
        :type ep_npc4: List[EPNpc4Single]
        """

        self._ep_npc4 = ep_npc4

    @property
    def ep_npc6(self):
        """Gets the ep_npc6 of this DDNMFFunctionSingleAllOf1.


        :return: The ep_npc6 of this DDNMFFunctionSingleAllOf1.
        :rtype: List[EPNpc6Single]
        """
        return self._ep_npc6

    @ep_npc6.setter
    def ep_npc6(self, ep_npc6):
        """Sets the ep_npc6 of this DDNMFFunctionSingleAllOf1.


        :param ep_npc6: The ep_npc6 of this DDNMFFunctionSingleAllOf1.
        :type ep_npc6: List[EPNpc6Single]
        """

        self._ep_npc6 = ep_npc6

    @property
    def ep_npc7(self):
        """Gets the ep_npc7 of this DDNMFFunctionSingleAllOf1.


        :return: The ep_npc7 of this DDNMFFunctionSingleAllOf1.
        :rtype: List[EPNpc7Single]
        """
        return self._ep_npc7

    @ep_npc7.setter
    def ep_npc7(self, ep_npc7):
        """Sets the ep_npc7 of this DDNMFFunctionSingleAllOf1.


        :param ep_npc7: The ep_npc7 of this DDNMFFunctionSingleAllOf1.
        :type ep_npc7: List[EPNpc7Single]
        """

        self._ep_npc7 = ep_npc7

    @property
    def ep_npc8(self):
        """Gets the ep_npc8 of this DDNMFFunctionSingleAllOf1.


        :return: The ep_npc8 of this DDNMFFunctionSingleAllOf1.
        :rtype: List[EPNpc8Single]
        """
        return self._ep_npc8

    @ep_npc8.setter
    def ep_npc8(self, ep_npc8):
        """Sets the ep_npc8 of this DDNMFFunctionSingleAllOf1.


        :param ep_npc8: The ep_npc8 of this DDNMFFunctionSingleAllOf1.
        :type ep_npc8: List[EPNpc8Single]
        """

        self._ep_npc8 = ep_npc8
