# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.dmro_function_single_all_of_attributes import DMROFunctionSingleAllOfAttributes
from openapi_server import util

from openapi_server.models.dmro_function_single_all_of_attributes import DMROFunctionSingleAllOfAttributes  # noqa: E501

class DMROFunctionSingleAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attributes=None):  # noqa: E501
        """DMROFunctionSingleAllOf - a model defined in OpenAPI

        :param attributes: The attributes of this DMROFunctionSingleAllOf.  # noqa: E501
        :type attributes: DMROFunctionSingleAllOfAttributes
        """
        self.openapi_types = {
            'attributes': DMROFunctionSingleAllOfAttributes
        }

        self.attribute_map = {
            'attributes': 'attributes'
        }

        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'DMROFunctionSingleAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DMROFunction_Single_allOf of this DMROFunctionSingleAllOf.  # noqa: E501
        :rtype: DMROFunctionSingleAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attributes(self):
        """Gets the attributes of this DMROFunctionSingleAllOf.


        :return: The attributes of this DMROFunctionSingleAllOf.
        :rtype: DMROFunctionSingleAllOfAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this DMROFunctionSingleAllOf.


        :param attributes: The attributes of this DMROFunctionSingleAllOf.
        :type attributes: DMROFunctionSingleAllOfAttributes
        """

        self._attributes = attributes
