# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.dynamic5_qi_set_single_all_of_attributes import Dynamic5QISetSingleAllOfAttributes
from openapi_server import util

from openapi_server.models.dynamic5_qi_set_single_all_of_attributes import Dynamic5QISetSingleAllOfAttributes  # noqa: E501

class Dynamic5QISetSingleAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attributes=None):  # noqa: E501
        """Dynamic5QISetSingleAllOf - a model defined in OpenAPI

        :param attributes: The attributes of this Dynamic5QISetSingleAllOf.  # noqa: E501
        :type attributes: Dynamic5QISetSingleAllOfAttributes
        """
        self.openapi_types = {
            'attributes': Dynamic5QISetSingleAllOfAttributes
        }

        self.attribute_map = {
            'attributes': 'attributes'
        }

        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'Dynamic5QISetSingleAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Dynamic5QISet_Single_allOf of this Dynamic5QISetSingleAllOf.  # noqa: E501
        :rtype: Dynamic5QISetSingleAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attributes(self):
        """Gets the attributes of this Dynamic5QISetSingleAllOf.


        :return: The attributes of this Dynamic5QISetSingleAllOf.
        :rtype: Dynamic5QISetSingleAllOfAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Dynamic5QISetSingleAllOf.


        :param attributes: The attributes of this Dynamic5QISetSingleAllOf.
        :type attributes: Dynamic5QISetSingleAllOfAttributes
        """

        self._attributes = attributes
