# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ErrorResponseError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error_info=None):  # noqa: E501
        """ErrorResponseError - a model defined in OpenAPI

        :param error_info: The error_info of this ErrorResponseError.  # noqa: E501
        :type error_info: str
        """
        self.openapi_types = {
            'error_info': str
        }

        self.attribute_map = {
            'error_info': 'errorInfo'
        }

        self._error_info = error_info

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponseError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse_error of this ErrorResponseError.  # noqa: E501
        :rtype: ErrorResponseError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_info(self):
        """Gets the error_info of this ErrorResponseError.


        :return: The error_info of this ErrorResponseError.
        :rtype: str
        """
        return self._error_info

    @error_info.setter
    def error_info(self, error_info):
        """Sets the error_info of this ErrorResponseError.


        :param error_info: The error_info of this ErrorResponseError.
        :type error_info: str
        """

        self._error_info = error_info
