# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.external_eu_tran_cell_single import ExternalEUTranCellSingle
from openapi_server import util

from openapi_server.models.external_eu_tran_cell_single import ExternalEUTranCellSingle  # noqa: E501

class ExternalENBFunctionSingleAllOf1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, external_eu_tran_cell=None):  # noqa: E501
        """ExternalENBFunctionSingleAllOf1 - a model defined in OpenAPI

        :param external_eu_tran_cell: The external_eu_tran_cell of this ExternalENBFunctionSingleAllOf1.  # noqa: E501
        :type external_eu_tran_cell: List[ExternalEUTranCellSingle]
        """
        self.openapi_types = {
            'external_eu_tran_cell': List[ExternalEUTranCellSingle]
        }

        self.attribute_map = {
            'external_eu_tran_cell': 'ExternalEUTranCell'
        }

        self._external_eu_tran_cell = external_eu_tran_cell

    @classmethod
    def from_dict(cls, dikt) -> 'ExternalENBFunctionSingleAllOf1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExternalENBFunction_Single_allOf_1 of this ExternalENBFunctionSingleAllOf1.  # noqa: E501
        :rtype: ExternalENBFunctionSingleAllOf1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def external_eu_tran_cell(self):
        """Gets the external_eu_tran_cell of this ExternalENBFunctionSingleAllOf1.


        :return: The external_eu_tran_cell of this ExternalENBFunctionSingleAllOf1.
        :rtype: List[ExternalEUTranCellSingle]
        """
        return self._external_eu_tran_cell

    @external_eu_tran_cell.setter
    def external_eu_tran_cell(self, external_eu_tran_cell):
        """Sets the external_eu_tran_cell of this ExternalENBFunctionSingleAllOf1.


        :param external_eu_tran_cell: The external_eu_tran_cell of this ExternalENBFunctionSingleAllOf1.
        :type external_eu_tran_cell: List[ExternalEUTranCellSingle]
        """

        self._external_eu_tran_cell = external_eu_tran_cell
