# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.pee_parameter import PeeParameter
from openapi_server.models.plmn_id import PlmnId
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup
from openapi_server.models.vnf_parameter import VnfParameter
from openapi_server import util

from openapi_server.models.pee_parameter import PeeParameter  # noqa: E501
from openapi_server.models.plmn_id import PlmnId  # noqa: E501
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup  # noqa: E501
from openapi_server.models.vnf_parameter import VnfParameter  # noqa: E501

class ExternalNrCellCuSingleAllOfAttributes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_label=None, vnf_parameters_list=None, pee_parameters_list=None, priority_label=None, supported_perf_metric_groups=None, supported_trace_metrics=None, cell_local_id=None, nr_pci=None, plmn_id_list=None, n_r_frequency_ref=None):  # noqa: E501
        """ExternalNrCellCuSingleAllOfAttributes - a model defined in OpenAPI

        :param user_label: The user_label of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type user_label: str
        :param vnf_parameters_list: The vnf_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type vnf_parameters_list: List[VnfParameter]
        :param pee_parameters_list: The pee_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type pee_parameters_list: List[PeeParameter]
        :param priority_label: The priority_label of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type priority_label: int
        :param supported_perf_metric_groups: The supported_perf_metric_groups of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        :param supported_trace_metrics: The supported_trace_metrics of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type supported_trace_metrics: List[str]
        :param cell_local_id: The cell_local_id of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type cell_local_id: int
        :param nr_pci: The nr_pci of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type nr_pci: int
        :param plmn_id_list: The plmn_id_list of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type plmn_id_list: List[PlmnId]
        :param n_r_frequency_ref: The n_r_frequency_ref of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :type n_r_frequency_ref: str
        """
        self.openapi_types = {
            'user_label': str,
            'vnf_parameters_list': List[VnfParameter],
            'pee_parameters_list': List[PeeParameter],
            'priority_label': int,
            'supported_perf_metric_groups': List[SupportedPerfMetricGroup],
            'supported_trace_metrics': List[str],
            'cell_local_id': int,
            'nr_pci': int,
            'plmn_id_list': List[PlmnId],
            'n_r_frequency_ref': str
        }

        self.attribute_map = {
            'user_label': 'userLabel',
            'vnf_parameters_list': 'vnfParametersList',
            'pee_parameters_list': 'peeParametersList',
            'priority_label': 'priorityLabel',
            'supported_perf_metric_groups': 'supportedPerfMetricGroups',
            'supported_trace_metrics': 'supportedTraceMetrics',
            'cell_local_id': 'cellLocalId',
            'nr_pci': 'nrPci',
            'plmn_id_list': 'plmnIdList',
            'n_r_frequency_ref': 'nRFrequencyRef'
        }

        self._user_label = user_label
        self._vnf_parameters_list = vnf_parameters_list
        self._pee_parameters_list = pee_parameters_list
        self._priority_label = priority_label
        self._supported_perf_metric_groups = supported_perf_metric_groups
        self._supported_trace_metrics = supported_trace_metrics
        self._cell_local_id = cell_local_id
        self._nr_pci = nr_pci
        self._plmn_id_list = plmn_id_list
        self._n_r_frequency_ref = n_r_frequency_ref

    @classmethod
    def from_dict(cls, dikt) -> 'ExternalNrCellCuSingleAllOfAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExternalNrCellCu_Single_allOf_attributes of this ExternalNrCellCuSingleAllOfAttributes.  # noqa: E501
        :rtype: ExternalNrCellCuSingleAllOfAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_label(self):
        """Gets the user_label of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The user_label of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: str
        """
        return self._user_label

    @user_label.setter
    def user_label(self, user_label):
        """Sets the user_label of this ExternalNrCellCuSingleAllOfAttributes.


        :param user_label: The user_label of this ExternalNrCellCuSingleAllOfAttributes.
        :type user_label: str
        """

        self._user_label = user_label

    @property
    def vnf_parameters_list(self):
        """Gets the vnf_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The vnf_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: List[VnfParameter]
        """
        return self._vnf_parameters_list

    @vnf_parameters_list.setter
    def vnf_parameters_list(self, vnf_parameters_list):
        """Sets the vnf_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.


        :param vnf_parameters_list: The vnf_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.
        :type vnf_parameters_list: List[VnfParameter]
        """

        self._vnf_parameters_list = vnf_parameters_list

    @property
    def pee_parameters_list(self):
        """Gets the pee_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The pee_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: List[PeeParameter]
        """
        return self._pee_parameters_list

    @pee_parameters_list.setter
    def pee_parameters_list(self, pee_parameters_list):
        """Sets the pee_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.


        :param pee_parameters_list: The pee_parameters_list of this ExternalNrCellCuSingleAllOfAttributes.
        :type pee_parameters_list: List[PeeParameter]
        """

        self._pee_parameters_list = pee_parameters_list

    @property
    def priority_label(self):
        """Gets the priority_label of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The priority_label of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: int
        """
        return self._priority_label

    @priority_label.setter
    def priority_label(self, priority_label):
        """Sets the priority_label of this ExternalNrCellCuSingleAllOfAttributes.


        :param priority_label: The priority_label of this ExternalNrCellCuSingleAllOfAttributes.
        :type priority_label: int
        """

        self._priority_label = priority_label

    @property
    def supported_perf_metric_groups(self):
        """Gets the supported_perf_metric_groups of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The supported_perf_metric_groups of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: List[SupportedPerfMetricGroup]
        """
        return self._supported_perf_metric_groups

    @supported_perf_metric_groups.setter
    def supported_perf_metric_groups(self, supported_perf_metric_groups):
        """Sets the supported_perf_metric_groups of this ExternalNrCellCuSingleAllOfAttributes.


        :param supported_perf_metric_groups: The supported_perf_metric_groups of this ExternalNrCellCuSingleAllOfAttributes.
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        """

        self._supported_perf_metric_groups = supported_perf_metric_groups

    @property
    def supported_trace_metrics(self):
        """Gets the supported_trace_metrics of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The supported_trace_metrics of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: List[str]
        """
        return self._supported_trace_metrics

    @supported_trace_metrics.setter
    def supported_trace_metrics(self, supported_trace_metrics):
        """Sets the supported_trace_metrics of this ExternalNrCellCuSingleAllOfAttributes.


        :param supported_trace_metrics: The supported_trace_metrics of this ExternalNrCellCuSingleAllOfAttributes.
        :type supported_trace_metrics: List[str]
        """

        self._supported_trace_metrics = supported_trace_metrics

    @property
    def cell_local_id(self):
        """Gets the cell_local_id of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The cell_local_id of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: int
        """
        return self._cell_local_id

    @cell_local_id.setter
    def cell_local_id(self, cell_local_id):
        """Sets the cell_local_id of this ExternalNrCellCuSingleAllOfAttributes.


        :param cell_local_id: The cell_local_id of this ExternalNrCellCuSingleAllOfAttributes.
        :type cell_local_id: int
        """

        self._cell_local_id = cell_local_id

    @property
    def nr_pci(self):
        """Gets the nr_pci of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The nr_pci of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: int
        """
        return self._nr_pci

    @nr_pci.setter
    def nr_pci(self, nr_pci):
        """Sets the nr_pci of this ExternalNrCellCuSingleAllOfAttributes.


        :param nr_pci: The nr_pci of this ExternalNrCellCuSingleAllOfAttributes.
        :type nr_pci: int
        """
        if nr_pci is not None and nr_pci > 503:  # noqa: E501
            raise ValueError("Invalid value for `nr_pci`, must be a value less than or equal to `503`")  # noqa: E501

        self._nr_pci = nr_pci

    @property
    def plmn_id_list(self):
        """Gets the plmn_id_list of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The plmn_id_list of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: List[PlmnId]
        """
        return self._plmn_id_list

    @plmn_id_list.setter
    def plmn_id_list(self, plmn_id_list):
        """Sets the plmn_id_list of this ExternalNrCellCuSingleAllOfAttributes.


        :param plmn_id_list: The plmn_id_list of this ExternalNrCellCuSingleAllOfAttributes.
        :type plmn_id_list: List[PlmnId]
        """

        self._plmn_id_list = plmn_id_list

    @property
    def n_r_frequency_ref(self):
        """Gets the n_r_frequency_ref of this ExternalNrCellCuSingleAllOfAttributes.


        :return: The n_r_frequency_ref of this ExternalNrCellCuSingleAllOfAttributes.
        :rtype: str
        """
        return self._n_r_frequency_ref

    @n_r_frequency_ref.setter
    def n_r_frequency_ref(self, n_r_frequency_ref):
        """Sets the n_r_frequency_ref of this ExternalNrCellCuSingleAllOfAttributes.


        :param n_r_frequency_ref: The n_r_frequency_ref of this ExternalNrCellCuSingleAllOfAttributes.
        :type n_r_frequency_ref: str
        """

        self._n_r_frequency_ref = n_r_frequency_ref
