# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.file_download_job_process_monitor import FileDownloadJobProcessMonitor
from openapi_server import util

from openapi_server.models.file_download_job_process_monitor import FileDownloadJobProcessMonitor  # noqa: E501

class FileDownloadJobSingleAllOfAttributes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, file_location=None, notification_recipient_address=None, cancel_job=None, job_monitor=None):  # noqa: E501
        """FileDownloadJobSingleAllOfAttributes - a model defined in OpenAPI

        :param file_location: The file_location of this FileDownloadJobSingleAllOfAttributes.  # noqa: E501
        :type file_location: str
        :param notification_recipient_address: The notification_recipient_address of this FileDownloadJobSingleAllOfAttributes.  # noqa: E501
        :type notification_recipient_address: str
        :param cancel_job: The cancel_job of this FileDownloadJobSingleAllOfAttributes.  # noqa: E501
        :type cancel_job: str
        :param job_monitor: The job_monitor of this FileDownloadJobSingleAllOfAttributes.  # noqa: E501
        :type job_monitor: FileDownloadJobProcessMonitor
        """
        self.openapi_types = {
            'file_location': str,
            'notification_recipient_address': str,
            'cancel_job': str,
            'job_monitor': FileDownloadJobProcessMonitor
        }

        self.attribute_map = {
            'file_location': 'fileLocation',
            'notification_recipient_address': 'notificationRecipientAddress',
            'cancel_job': 'cancelJob',
            'job_monitor': 'jobMonitor'
        }

        self._file_location = file_location
        self._notification_recipient_address = notification_recipient_address
        self._cancel_job = cancel_job
        self._job_monitor = job_monitor

    @classmethod
    def from_dict(cls, dikt) -> 'FileDownloadJobSingleAllOfAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileDownloadJob_Single_allOf_attributes of this FileDownloadJobSingleAllOfAttributes.  # noqa: E501
        :rtype: FileDownloadJobSingleAllOfAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_location(self):
        """Gets the file_location of this FileDownloadJobSingleAllOfAttributes.


        :return: The file_location of this FileDownloadJobSingleAllOfAttributes.
        :rtype: str
        """
        return self._file_location

    @file_location.setter
    def file_location(self, file_location):
        """Sets the file_location of this FileDownloadJobSingleAllOfAttributes.


        :param file_location: The file_location of this FileDownloadJobSingleAllOfAttributes.
        :type file_location: str
        """

        self._file_location = file_location

    @property
    def notification_recipient_address(self):
        """Gets the notification_recipient_address of this FileDownloadJobSingleAllOfAttributes.


        :return: The notification_recipient_address of this FileDownloadJobSingleAllOfAttributes.
        :rtype: str
        """
        return self._notification_recipient_address

    @notification_recipient_address.setter
    def notification_recipient_address(self, notification_recipient_address):
        """Sets the notification_recipient_address of this FileDownloadJobSingleAllOfAttributes.


        :param notification_recipient_address: The notification_recipient_address of this FileDownloadJobSingleAllOfAttributes.
        :type notification_recipient_address: str
        """

        self._notification_recipient_address = notification_recipient_address

    @property
    def cancel_job(self):
        """Gets the cancel_job of this FileDownloadJobSingleAllOfAttributes.


        :return: The cancel_job of this FileDownloadJobSingleAllOfAttributes.
        :rtype: str
        """
        return self._cancel_job

    @cancel_job.setter
    def cancel_job(self, cancel_job):
        """Sets the cancel_job of this FileDownloadJobSingleAllOfAttributes.


        :param cancel_job: The cancel_job of this FileDownloadJobSingleAllOfAttributes.
        :type cancel_job: str
        """
        allowed_values = ["true", "false"]  # noqa: E501
        if cancel_job not in allowed_values:
            raise ValueError(
                "Invalid value for `cancel_job` ({0}), must be one of {1}"
                .format(cancel_job, allowed_values)
            )

        self._cancel_job = cancel_job

    @property
    def job_monitor(self):
        """Gets the job_monitor of this FileDownloadJobSingleAllOfAttributes.


        :return: The job_monitor of this FileDownloadJobSingleAllOfAttributes.
        :rtype: FileDownloadJobProcessMonitor
        """
        return self._job_monitor

    @job_monitor.setter
    def job_monitor(self, job_monitor):
        """Sets the job_monitor of this FileDownloadJobSingleAllOfAttributes.


        :param job_monitor: The job_monitor of this FileDownloadJobSingleAllOfAttributes.
        :type job_monitor: FileDownloadJobProcessMonitor
        """

        self._job_monitor = job_monitor
