# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.pee_parameter import PeeParameter
from openapi_server.models.rim_rs_report_conf import RimRSReportConf
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup
from openapi_server.models.vnf_parameter import VnfParameter
from openapi_server import util

from openapi_server.models.pee_parameter import PeeParameter  # noqa: E501
from openapi_server.models.rim_rs_report_conf import RimRSReportConf  # noqa: E501
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup  # noqa: E501
from openapi_server.models.vnf_parameter import VnfParameter  # noqa: E501

class GnbDuFunctionSingleAllOfAttributes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_label=None, vnf_parameters_list=None, pee_parameters_list=None, priority_label=None, supported_perf_metric_groups=None, supported_trace_metrics=None, gnb_du_id=None, gnb_du_name=None, gnb_id=None, gnb_id_length=None, rim_rs_report_conf=None):  # noqa: E501
        """GnbDuFunctionSingleAllOfAttributes - a model defined in OpenAPI

        :param user_label: The user_label of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type user_label: str
        :param vnf_parameters_list: The vnf_parameters_list of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type vnf_parameters_list: List[VnfParameter]
        :param pee_parameters_list: The pee_parameters_list of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type pee_parameters_list: List[PeeParameter]
        :param priority_label: The priority_label of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type priority_label: int
        :param supported_perf_metric_groups: The supported_perf_metric_groups of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        :param supported_trace_metrics: The supported_trace_metrics of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type supported_trace_metrics: List[str]
        :param gnb_du_id: The gnb_du_id of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type gnb_du_id: float
        :param gnb_du_name: The gnb_du_name of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type gnb_du_name: str
        :param gnb_id: The gnb_id of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type gnb_id: str
        :param gnb_id_length: The gnb_id_length of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type gnb_id_length: int
        :param rim_rs_report_conf: The rim_rs_report_conf of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :type rim_rs_report_conf: RimRSReportConf
        """
        self.openapi_types = {
            'user_label': str,
            'vnf_parameters_list': List[VnfParameter],
            'pee_parameters_list': List[PeeParameter],
            'priority_label': int,
            'supported_perf_metric_groups': List[SupportedPerfMetricGroup],
            'supported_trace_metrics': List[str],
            'gnb_du_id': float,
            'gnb_du_name': str,
            'gnb_id': str,
            'gnb_id_length': int,
            'rim_rs_report_conf': RimRSReportConf
        }

        self.attribute_map = {
            'user_label': 'userLabel',
            'vnf_parameters_list': 'vnfParametersList',
            'pee_parameters_list': 'peeParametersList',
            'priority_label': 'priorityLabel',
            'supported_perf_metric_groups': 'supportedPerfMetricGroups',
            'supported_trace_metrics': 'supportedTraceMetrics',
            'gnb_du_id': 'gnbDuId',
            'gnb_du_name': 'gnbDuName',
            'gnb_id': 'gnbId',
            'gnb_id_length': 'gnbIdLength',
            'rim_rs_report_conf': 'rimRSReportConf'
        }

        self._user_label = user_label
        self._vnf_parameters_list = vnf_parameters_list
        self._pee_parameters_list = pee_parameters_list
        self._priority_label = priority_label
        self._supported_perf_metric_groups = supported_perf_metric_groups
        self._supported_trace_metrics = supported_trace_metrics
        self._gnb_du_id = gnb_du_id
        self._gnb_du_name = gnb_du_name
        self._gnb_id = gnb_id
        self._gnb_id_length = gnb_id_length
        self._rim_rs_report_conf = rim_rs_report_conf

    @classmethod
    def from_dict(cls, dikt) -> 'GnbDuFunctionSingleAllOfAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GnbDuFunction_Single_allOf_attributes of this GnbDuFunctionSingleAllOfAttributes.  # noqa: E501
        :rtype: GnbDuFunctionSingleAllOfAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_label(self):
        """Gets the user_label of this GnbDuFunctionSingleAllOfAttributes.


        :return: The user_label of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._user_label

    @user_label.setter
    def user_label(self, user_label):
        """Sets the user_label of this GnbDuFunctionSingleAllOfAttributes.


        :param user_label: The user_label of this GnbDuFunctionSingleAllOfAttributes.
        :type user_label: str
        """

        self._user_label = user_label

    @property
    def vnf_parameters_list(self):
        """Gets the vnf_parameters_list of this GnbDuFunctionSingleAllOfAttributes.


        :return: The vnf_parameters_list of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: List[VnfParameter]
        """
        return self._vnf_parameters_list

    @vnf_parameters_list.setter
    def vnf_parameters_list(self, vnf_parameters_list):
        """Sets the vnf_parameters_list of this GnbDuFunctionSingleAllOfAttributes.


        :param vnf_parameters_list: The vnf_parameters_list of this GnbDuFunctionSingleAllOfAttributes.
        :type vnf_parameters_list: List[VnfParameter]
        """

        self._vnf_parameters_list = vnf_parameters_list

    @property
    def pee_parameters_list(self):
        """Gets the pee_parameters_list of this GnbDuFunctionSingleAllOfAttributes.


        :return: The pee_parameters_list of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: List[PeeParameter]
        """
        return self._pee_parameters_list

    @pee_parameters_list.setter
    def pee_parameters_list(self, pee_parameters_list):
        """Sets the pee_parameters_list of this GnbDuFunctionSingleAllOfAttributes.


        :param pee_parameters_list: The pee_parameters_list of this GnbDuFunctionSingleAllOfAttributes.
        :type pee_parameters_list: List[PeeParameter]
        """

        self._pee_parameters_list = pee_parameters_list

    @property
    def priority_label(self):
        """Gets the priority_label of this GnbDuFunctionSingleAllOfAttributes.


        :return: The priority_label of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: int
        """
        return self._priority_label

    @priority_label.setter
    def priority_label(self, priority_label):
        """Sets the priority_label of this GnbDuFunctionSingleAllOfAttributes.


        :param priority_label: The priority_label of this GnbDuFunctionSingleAllOfAttributes.
        :type priority_label: int
        """

        self._priority_label = priority_label

    @property
    def supported_perf_metric_groups(self):
        """Gets the supported_perf_metric_groups of this GnbDuFunctionSingleAllOfAttributes.


        :return: The supported_perf_metric_groups of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: List[SupportedPerfMetricGroup]
        """
        return self._supported_perf_metric_groups

    @supported_perf_metric_groups.setter
    def supported_perf_metric_groups(self, supported_perf_metric_groups):
        """Sets the supported_perf_metric_groups of this GnbDuFunctionSingleAllOfAttributes.


        :param supported_perf_metric_groups: The supported_perf_metric_groups of this GnbDuFunctionSingleAllOfAttributes.
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        """

        self._supported_perf_metric_groups = supported_perf_metric_groups

    @property
    def supported_trace_metrics(self):
        """Gets the supported_trace_metrics of this GnbDuFunctionSingleAllOfAttributes.


        :return: The supported_trace_metrics of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: List[str]
        """
        return self._supported_trace_metrics

    @supported_trace_metrics.setter
    def supported_trace_metrics(self, supported_trace_metrics):
        """Sets the supported_trace_metrics of this GnbDuFunctionSingleAllOfAttributes.


        :param supported_trace_metrics: The supported_trace_metrics of this GnbDuFunctionSingleAllOfAttributes.
        :type supported_trace_metrics: List[str]
        """

        self._supported_trace_metrics = supported_trace_metrics

    @property
    def gnb_du_id(self):
        """Gets the gnb_du_id of this GnbDuFunctionSingleAllOfAttributes.


        :return: The gnb_du_id of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: float
        """
        return self._gnb_du_id

    @gnb_du_id.setter
    def gnb_du_id(self, gnb_du_id):
        """Sets the gnb_du_id of this GnbDuFunctionSingleAllOfAttributes.


        :param gnb_du_id: The gnb_du_id of this GnbDuFunctionSingleAllOfAttributes.
        :type gnb_du_id: float
        """
        if gnb_du_id is not None and gnb_du_id > 68719476735:  # noqa: E501
            raise ValueError("Invalid value for `gnb_du_id`, must be a value less than or equal to `68719476735`")  # noqa: E501
        if gnb_du_id is not None and gnb_du_id < 0:  # noqa: E501
            raise ValueError("Invalid value for `gnb_du_id`, must be a value greater than or equal to `0`")  # noqa: E501

        self._gnb_du_id = gnb_du_id

    @property
    def gnb_du_name(self):
        """Gets the gnb_du_name of this GnbDuFunctionSingleAllOfAttributes.


        :return: The gnb_du_name of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._gnb_du_name

    @gnb_du_name.setter
    def gnb_du_name(self, gnb_du_name):
        """Sets the gnb_du_name of this GnbDuFunctionSingleAllOfAttributes.


        :param gnb_du_name: The gnb_du_name of this GnbDuFunctionSingleAllOfAttributes.
        :type gnb_du_name: str
        """
        if gnb_du_name is not None and len(gnb_du_name) > 150:
            raise ValueError("Invalid value for `gnb_du_name`, length must be less than or equal to `150`")  # noqa: E501

        self._gnb_du_name = gnb_du_name

    @property
    def gnb_id(self):
        """Gets the gnb_id of this GnbDuFunctionSingleAllOfAttributes.


        :return: The gnb_id of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._gnb_id

    @gnb_id.setter
    def gnb_id(self, gnb_id):
        """Sets the gnb_id of this GnbDuFunctionSingleAllOfAttributes.


        :param gnb_id: The gnb_id of this GnbDuFunctionSingleAllOfAttributes.
        :type gnb_id: str
        """

        self._gnb_id = gnb_id

    @property
    def gnb_id_length(self):
        """Gets the gnb_id_length of this GnbDuFunctionSingleAllOfAttributes.


        :return: The gnb_id_length of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: int
        """
        return self._gnb_id_length

    @gnb_id_length.setter
    def gnb_id_length(self, gnb_id_length):
        """Sets the gnb_id_length of this GnbDuFunctionSingleAllOfAttributes.


        :param gnb_id_length: The gnb_id_length of this GnbDuFunctionSingleAllOfAttributes.
        :type gnb_id_length: int
        """
        if gnb_id_length is not None and gnb_id_length > 32:  # noqa: E501
            raise ValueError("Invalid value for `gnb_id_length`, must be a value less than or equal to `32`")  # noqa: E501
        if gnb_id_length is not None and gnb_id_length < 22:  # noqa: E501
            raise ValueError("Invalid value for `gnb_id_length`, must be a value greater than or equal to `22`")  # noqa: E501

        self._gnb_id_length = gnb_id_length

    @property
    def rim_rs_report_conf(self):
        """Gets the rim_rs_report_conf of this GnbDuFunctionSingleAllOfAttributes.


        :return: The rim_rs_report_conf of this GnbDuFunctionSingleAllOfAttributes.
        :rtype: RimRSReportConf
        """
        return self._rim_rs_report_conf

    @rim_rs_report_conf.setter
    def rim_rs_report_conf(self, rim_rs_report_conf):
        """Sets the rim_rs_report_conf of this GnbDuFunctionSingleAllOfAttributes.


        :param rim_rs_report_conf: The rim_rs_report_conf of this GnbDuFunctionSingleAllOfAttributes.
        :type rim_rs_report_conf: RimRSReportConf
        """

        self._rim_rs_report_conf = rim_rs_report_conf
