# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.plmn_info import PlmnInfo
from openapi_server import util

from openapi_server.models.plmn_info import PlmnInfo  # noqa: E501

class GnbCuUpFunctionSingleAllOfAttributesAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, gnb_id=None, gnb_id_length=None, gnb_cu_up_id=None, plmn_info_list=None, configurable5_qi_set_ref=None, dynamic5_qi_set_ref=None):  # noqa: E501
        """GnbCuUpFunctionSingleAllOfAttributesAllOf - a model defined in OpenAPI

        :param gnb_id: The gnb_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :type gnb_id: str
        :param gnb_id_length: The gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :type gnb_id_length: int
        :param gnb_cu_up_id: The gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :type gnb_cu_up_id: float
        :param plmn_info_list: The plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :type plmn_info_list: List[PlmnInfo]
        :param configurable5_qi_set_ref: The configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :type configurable5_qi_set_ref: str
        :param dynamic5_qi_set_ref: The dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :type dynamic5_qi_set_ref: str
        """
        self.openapi_types = {
            'gnb_id': str,
            'gnb_id_length': int,
            'gnb_cu_up_id': float,
            'plmn_info_list': List[PlmnInfo],
            'configurable5_qi_set_ref': str,
            'dynamic5_qi_set_ref': str
        }

        self.attribute_map = {
            'gnb_id': 'gnbId',
            'gnb_id_length': 'gnbIdLength',
            'gnb_cu_up_id': 'gnbCuUpId',
            'plmn_info_list': 'plmnInfoList',
            'configurable5_qi_set_ref': 'configurable5QISetRef',
            'dynamic5_qi_set_ref': 'dynamic5QISetRef'
        }

        self._gnb_id = gnb_id
        self._gnb_id_length = gnb_id_length
        self._gnb_cu_up_id = gnb_cu_up_id
        self._plmn_info_list = plmn_info_list
        self._configurable5_qi_set_ref = configurable5_qi_set_ref
        self._dynamic5_qi_set_ref = dynamic5_qi_set_ref

    @classmethod
    def from_dict(cls, dikt) -> 'GnbCuUpFunctionSingleAllOfAttributesAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GnbCuUpFunction_Single_allOf_attributes_allOf of this GnbCuUpFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :rtype: GnbCuUpFunctionSingleAllOfAttributesAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def gnb_id(self):
        """Gets the gnb_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :return: The gnb_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :rtype: str
        """
        return self._gnb_id

    @gnb_id.setter
    def gnb_id(self, gnb_id):
        """Sets the gnb_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :param gnb_id: The gnb_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :type gnb_id: str
        """

        self._gnb_id = gnb_id

    @property
    def gnb_id_length(self):
        """Gets the gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :return: The gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :rtype: int
        """
        return self._gnb_id_length

    @gnb_id_length.setter
    def gnb_id_length(self, gnb_id_length):
        """Sets the gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :param gnb_id_length: The gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :type gnb_id_length: int
        """
        if gnb_id_length is not None and gnb_id_length > 32:  # noqa: E501
            raise ValueError("Invalid value for `gnb_id_length`, must be a value less than or equal to `32`")  # noqa: E501
        if gnb_id_length is not None and gnb_id_length < 22:  # noqa: E501
            raise ValueError("Invalid value for `gnb_id_length`, must be a value greater than or equal to `22`")  # noqa: E501

        self._gnb_id_length = gnb_id_length

    @property
    def gnb_cu_up_id(self):
        """Gets the gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :return: The gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :rtype: float
        """
        return self._gnb_cu_up_id

    @gnb_cu_up_id.setter
    def gnb_cu_up_id(self, gnb_cu_up_id):
        """Sets the gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :param gnb_cu_up_id: The gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :type gnb_cu_up_id: float
        """
        if gnb_cu_up_id is not None and gnb_cu_up_id > 68719476735:  # noqa: E501
            raise ValueError("Invalid value for `gnb_cu_up_id`, must be a value less than or equal to `68719476735`")  # noqa: E501
        if gnb_cu_up_id is not None and gnb_cu_up_id < 0:  # noqa: E501
            raise ValueError("Invalid value for `gnb_cu_up_id`, must be a value greater than or equal to `0`")  # noqa: E501

        self._gnb_cu_up_id = gnb_cu_up_id

    @property
    def plmn_info_list(self):
        """Gets the plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :return: The plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :rtype: List[PlmnInfo]
        """
        return self._plmn_info_list

    @plmn_info_list.setter
    def plmn_info_list(self, plmn_info_list):
        """Sets the plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :param plmn_info_list: The plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :type plmn_info_list: List[PlmnInfo]
        """

        self._plmn_info_list = plmn_info_list

    @property
    def configurable5_qi_set_ref(self):
        """Gets the configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :return: The configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :rtype: str
        """
        return self._configurable5_qi_set_ref

    @configurable5_qi_set_ref.setter
    def configurable5_qi_set_ref(self, configurable5_qi_set_ref):
        """Sets the configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :param configurable5_qi_set_ref: The configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :type configurable5_qi_set_ref: str
        """

        self._configurable5_qi_set_ref = configurable5_qi_set_ref

    @property
    def dynamic5_qi_set_ref(self):
        """Gets the dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :return: The dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :rtype: str
        """
        return self._dynamic5_qi_set_ref

    @dynamic5_qi_set_ref.setter
    def dynamic5_qi_set_ref(self, dynamic5_qi_set_ref):
        """Sets the dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.


        :param dynamic5_qi_set_ref: The dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributesAllOf.
        :type dynamic5_qi_set_ref: str
        """

        self._dynamic5_qi_set_ref = dynamic5_qi_set_ref
