# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.pee_parameter import PeeParameter
from openapi_server.models.plmn_info import PlmnInfo
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup
from openapi_server.models.vnf_parameter import VnfParameter
from openapi_server import util

from openapi_server.models.pee_parameter import PeeParameter  # noqa: E501
from openapi_server.models.plmn_info import PlmnInfo  # noqa: E501
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup  # noqa: E501
from openapi_server.models.vnf_parameter import VnfParameter  # noqa: E501

class GnbCuUpFunctionSingleAllOfAttributes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_label=None, vnf_parameters_list=None, pee_parameters_list=None, priority_label=None, supported_perf_metric_groups=None, supported_trace_metrics=None, gnb_id=None, gnb_id_length=None, gnb_cu_up_id=None, plmn_info_list=None, configurable5_qi_set_ref=None, dynamic5_qi_set_ref=None):  # noqa: E501
        """GnbCuUpFunctionSingleAllOfAttributes - a model defined in OpenAPI

        :param user_label: The user_label of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type user_label: str
        :param vnf_parameters_list: The vnf_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type vnf_parameters_list: List[VnfParameter]
        :param pee_parameters_list: The pee_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type pee_parameters_list: List[PeeParameter]
        :param priority_label: The priority_label of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type priority_label: int
        :param supported_perf_metric_groups: The supported_perf_metric_groups of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        :param supported_trace_metrics: The supported_trace_metrics of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type supported_trace_metrics: List[str]
        :param gnb_id: The gnb_id of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type gnb_id: str
        :param gnb_id_length: The gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type gnb_id_length: int
        :param gnb_cu_up_id: The gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type gnb_cu_up_id: float
        :param plmn_info_list: The plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type plmn_info_list: List[PlmnInfo]
        :param configurable5_qi_set_ref: The configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type configurable5_qi_set_ref: str
        :param dynamic5_qi_set_ref: The dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :type dynamic5_qi_set_ref: str
        """
        self.openapi_types = {
            'user_label': str,
            'vnf_parameters_list': List[VnfParameter],
            'pee_parameters_list': List[PeeParameter],
            'priority_label': int,
            'supported_perf_metric_groups': List[SupportedPerfMetricGroup],
            'supported_trace_metrics': List[str],
            'gnb_id': str,
            'gnb_id_length': int,
            'gnb_cu_up_id': float,
            'plmn_info_list': List[PlmnInfo],
            'configurable5_qi_set_ref': str,
            'dynamic5_qi_set_ref': str
        }

        self.attribute_map = {
            'user_label': 'userLabel',
            'vnf_parameters_list': 'vnfParametersList',
            'pee_parameters_list': 'peeParametersList',
            'priority_label': 'priorityLabel',
            'supported_perf_metric_groups': 'supportedPerfMetricGroups',
            'supported_trace_metrics': 'supportedTraceMetrics',
            'gnb_id': 'gnbId',
            'gnb_id_length': 'gnbIdLength',
            'gnb_cu_up_id': 'gnbCuUpId',
            'plmn_info_list': 'plmnInfoList',
            'configurable5_qi_set_ref': 'configurable5QISetRef',
            'dynamic5_qi_set_ref': 'dynamic5QISetRef'
        }

        self._user_label = user_label
        self._vnf_parameters_list = vnf_parameters_list
        self._pee_parameters_list = pee_parameters_list
        self._priority_label = priority_label
        self._supported_perf_metric_groups = supported_perf_metric_groups
        self._supported_trace_metrics = supported_trace_metrics
        self._gnb_id = gnb_id
        self._gnb_id_length = gnb_id_length
        self._gnb_cu_up_id = gnb_cu_up_id
        self._plmn_info_list = plmn_info_list
        self._configurable5_qi_set_ref = configurable5_qi_set_ref
        self._dynamic5_qi_set_ref = dynamic5_qi_set_ref

    @classmethod
    def from_dict(cls, dikt) -> 'GnbCuUpFunctionSingleAllOfAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GnbCuUpFunction_Single_allOf_attributes of this GnbCuUpFunctionSingleAllOfAttributes.  # noqa: E501
        :rtype: GnbCuUpFunctionSingleAllOfAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_label(self):
        """Gets the user_label of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The user_label of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._user_label

    @user_label.setter
    def user_label(self, user_label):
        """Sets the user_label of this GnbCuUpFunctionSingleAllOfAttributes.


        :param user_label: The user_label of this GnbCuUpFunctionSingleAllOfAttributes.
        :type user_label: str
        """

        self._user_label = user_label

    @property
    def vnf_parameters_list(self):
        """Gets the vnf_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The vnf_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: List[VnfParameter]
        """
        return self._vnf_parameters_list

    @vnf_parameters_list.setter
    def vnf_parameters_list(self, vnf_parameters_list):
        """Sets the vnf_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.


        :param vnf_parameters_list: The vnf_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.
        :type vnf_parameters_list: List[VnfParameter]
        """

        self._vnf_parameters_list = vnf_parameters_list

    @property
    def pee_parameters_list(self):
        """Gets the pee_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The pee_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: List[PeeParameter]
        """
        return self._pee_parameters_list

    @pee_parameters_list.setter
    def pee_parameters_list(self, pee_parameters_list):
        """Sets the pee_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.


        :param pee_parameters_list: The pee_parameters_list of this GnbCuUpFunctionSingleAllOfAttributes.
        :type pee_parameters_list: List[PeeParameter]
        """

        self._pee_parameters_list = pee_parameters_list

    @property
    def priority_label(self):
        """Gets the priority_label of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The priority_label of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: int
        """
        return self._priority_label

    @priority_label.setter
    def priority_label(self, priority_label):
        """Sets the priority_label of this GnbCuUpFunctionSingleAllOfAttributes.


        :param priority_label: The priority_label of this GnbCuUpFunctionSingleAllOfAttributes.
        :type priority_label: int
        """

        self._priority_label = priority_label

    @property
    def supported_perf_metric_groups(self):
        """Gets the supported_perf_metric_groups of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The supported_perf_metric_groups of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: List[SupportedPerfMetricGroup]
        """
        return self._supported_perf_metric_groups

    @supported_perf_metric_groups.setter
    def supported_perf_metric_groups(self, supported_perf_metric_groups):
        """Sets the supported_perf_metric_groups of this GnbCuUpFunctionSingleAllOfAttributes.


        :param supported_perf_metric_groups: The supported_perf_metric_groups of this GnbCuUpFunctionSingleAllOfAttributes.
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        """

        self._supported_perf_metric_groups = supported_perf_metric_groups

    @property
    def supported_trace_metrics(self):
        """Gets the supported_trace_metrics of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The supported_trace_metrics of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: List[str]
        """
        return self._supported_trace_metrics

    @supported_trace_metrics.setter
    def supported_trace_metrics(self, supported_trace_metrics):
        """Sets the supported_trace_metrics of this GnbCuUpFunctionSingleAllOfAttributes.


        :param supported_trace_metrics: The supported_trace_metrics of this GnbCuUpFunctionSingleAllOfAttributes.
        :type supported_trace_metrics: List[str]
        """

        self._supported_trace_metrics = supported_trace_metrics

    @property
    def gnb_id(self):
        """Gets the gnb_id of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The gnb_id of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._gnb_id

    @gnb_id.setter
    def gnb_id(self, gnb_id):
        """Sets the gnb_id of this GnbCuUpFunctionSingleAllOfAttributes.


        :param gnb_id: The gnb_id of this GnbCuUpFunctionSingleAllOfAttributes.
        :type gnb_id: str
        """

        self._gnb_id = gnb_id

    @property
    def gnb_id_length(self):
        """Gets the gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: int
        """
        return self._gnb_id_length

    @gnb_id_length.setter
    def gnb_id_length(self, gnb_id_length):
        """Sets the gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributes.


        :param gnb_id_length: The gnb_id_length of this GnbCuUpFunctionSingleAllOfAttributes.
        :type gnb_id_length: int
        """
        if gnb_id_length is not None and gnb_id_length > 32:  # noqa: E501
            raise ValueError("Invalid value for `gnb_id_length`, must be a value less than or equal to `32`")  # noqa: E501
        if gnb_id_length is not None and gnb_id_length < 22:  # noqa: E501
            raise ValueError("Invalid value for `gnb_id_length`, must be a value greater than or equal to `22`")  # noqa: E501

        self._gnb_id_length = gnb_id_length

    @property
    def gnb_cu_up_id(self):
        """Gets the gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: float
        """
        return self._gnb_cu_up_id

    @gnb_cu_up_id.setter
    def gnb_cu_up_id(self, gnb_cu_up_id):
        """Sets the gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributes.


        :param gnb_cu_up_id: The gnb_cu_up_id of this GnbCuUpFunctionSingleAllOfAttributes.
        :type gnb_cu_up_id: float
        """
        if gnb_cu_up_id is not None and gnb_cu_up_id > 68719476735:  # noqa: E501
            raise ValueError("Invalid value for `gnb_cu_up_id`, must be a value less than or equal to `68719476735`")  # noqa: E501
        if gnb_cu_up_id is not None and gnb_cu_up_id < 0:  # noqa: E501
            raise ValueError("Invalid value for `gnb_cu_up_id`, must be a value greater than or equal to `0`")  # noqa: E501

        self._gnb_cu_up_id = gnb_cu_up_id

    @property
    def plmn_info_list(self):
        """Gets the plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: List[PlmnInfo]
        """
        return self._plmn_info_list

    @plmn_info_list.setter
    def plmn_info_list(self, plmn_info_list):
        """Sets the plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributes.


        :param plmn_info_list: The plmn_info_list of this GnbCuUpFunctionSingleAllOfAttributes.
        :type plmn_info_list: List[PlmnInfo]
        """

        self._plmn_info_list = plmn_info_list

    @property
    def configurable5_qi_set_ref(self):
        """Gets the configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._configurable5_qi_set_ref

    @configurable5_qi_set_ref.setter
    def configurable5_qi_set_ref(self, configurable5_qi_set_ref):
        """Sets the configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.


        :param configurable5_qi_set_ref: The configurable5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.
        :type configurable5_qi_set_ref: str
        """

        self._configurable5_qi_set_ref = configurable5_qi_set_ref

    @property
    def dynamic5_qi_set_ref(self):
        """Gets the dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.


        :return: The dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._dynamic5_qi_set_ref

    @dynamic5_qi_set_ref.setter
    def dynamic5_qi_set_ref(self, dynamic5_qi_set_ref):
        """Sets the dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.


        :param dynamic5_qi_set_ref: The dynamic5_qi_set_ref of this GnbCuUpFunctionSingleAllOfAttributes.
        :type dynamic5_qi_set_ref: str
        """

        self._dynamic5_qi_set_ref = dynamic5_qi_set_ref
