# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.fulfilment_info import FulfilmentInfo
from openapi_server.models.intent_context import IntentContext
from openapi_server.models.intent_single_all_of_intent_expectations_inner import IntentSingleAllOfIntentExpectationsInner
from openapi_server import util

from openapi_server.models.fulfilment_info import FulfilmentInfo  # noqa: E501
from openapi_server.models.intent_context import IntentContext  # noqa: E501
from openapi_server.models.intent_single_all_of_intent_expectations_inner import IntentSingleAllOfIntentExpectationsInner  # noqa: E501

class IntentSingleAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_label=None, intent_expectations=None, intent_contexts=None, intent_fulfilment_info=None):  # noqa: E501
        """IntentSingleAllOf - a model defined in OpenAPI

        :param user_label: The user_label of this IntentSingleAllOf.  # noqa: E501
        :type user_label: str
        :param intent_expectations: The intent_expectations of this IntentSingleAllOf.  # noqa: E501
        :type intent_expectations: List[IntentSingleAllOfIntentExpectationsInner]
        :param intent_contexts: The intent_contexts of this IntentSingleAllOf.  # noqa: E501
        :type intent_contexts: List[IntentContext]
        :param intent_fulfilment_info: The intent_fulfilment_info of this IntentSingleAllOf.  # noqa: E501
        :type intent_fulfilment_info: FulfilmentInfo
        """
        self.openapi_types = {
            'user_label': str,
            'intent_expectations': List[IntentSingleAllOfIntentExpectationsInner],
            'intent_contexts': List[IntentContext],
            'intent_fulfilment_info': FulfilmentInfo
        }

        self.attribute_map = {
            'user_label': 'userLabel',
            'intent_expectations': 'intentExpectations',
            'intent_contexts': 'intentContexts',
            'intent_fulfilment_info': 'intentFulfilmentInfo'
        }

        self._user_label = user_label
        self._intent_expectations = intent_expectations
        self._intent_contexts = intent_contexts
        self._intent_fulfilment_info = intent_fulfilment_info

    @classmethod
    def from_dict(cls, dikt) -> 'IntentSingleAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Intent_Single_allOf of this IntentSingleAllOf.  # noqa: E501
        :rtype: IntentSingleAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_label(self):
        """Gets the user_label of this IntentSingleAllOf.


        :return: The user_label of this IntentSingleAllOf.
        :rtype: str
        """
        return self._user_label

    @user_label.setter
    def user_label(self, user_label):
        """Sets the user_label of this IntentSingleAllOf.


        :param user_label: The user_label of this IntentSingleAllOf.
        :type user_label: str
        """

        self._user_label = user_label

    @property
    def intent_expectations(self):
        """Gets the intent_expectations of this IntentSingleAllOf.


        :return: The intent_expectations of this IntentSingleAllOf.
        :rtype: List[IntentSingleAllOfIntentExpectationsInner]
        """
        return self._intent_expectations

    @intent_expectations.setter
    def intent_expectations(self, intent_expectations):
        """Sets the intent_expectations of this IntentSingleAllOf.


        :param intent_expectations: The intent_expectations of this IntentSingleAllOf.
        :type intent_expectations: List[IntentSingleAllOfIntentExpectationsInner]
        """

        self._intent_expectations = intent_expectations

    @property
    def intent_contexts(self):
        """Gets the intent_contexts of this IntentSingleAllOf.


        :return: The intent_contexts of this IntentSingleAllOf.
        :rtype: List[IntentContext]
        """
        return self._intent_contexts

    @intent_contexts.setter
    def intent_contexts(self, intent_contexts):
        """Sets the intent_contexts of this IntentSingleAllOf.


        :param intent_contexts: The intent_contexts of this IntentSingleAllOf.
        :type intent_contexts: List[IntentContext]
        """

        self._intent_contexts = intent_contexts

    @property
    def intent_fulfilment_info(self):
        """Gets the intent_fulfilment_info of this IntentSingleAllOf.


        :return: The intent_fulfilment_info of this IntentSingleAllOf.
        :rtype: FulfilmentInfo
        """
        return self._intent_fulfilment_info

    @intent_fulfilment_info.setter
    def intent_fulfilment_info(self, intent_fulfilment_info):
        """Sets the intent_fulfilment_info of this IntentSingleAllOf.


        :param intent_fulfilment_info: The intent_fulfilment_info of this IntentSingleAllOf.
        :type intent_fulfilment_info: FulfilmentInfo
        """

        self._intent_fulfilment_info = intent_fulfilment_info
