# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ListOfMeasurementsType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, umts=None, lte=None, nr=None):  # noqa: E501
        """ListOfMeasurementsType - a model defined in OpenAPI

        :param umts: The umts of this ListOfMeasurementsType.  # noqa: E501
        :type umts: List[str]
        :param lte: The lte of this ListOfMeasurementsType.  # noqa: E501
        :type lte: List[str]
        :param nr: The nr of this ListOfMeasurementsType.  # noqa: E501
        :type nr: List[str]
        """
        self.openapi_types = {
            'umts': List[str],
            'lte': List[str],
            'nr': List[str]
        }

        self.attribute_map = {
            'umts': 'UMTS',
            'lte': 'LTE',
            'nr': 'NR'
        }

        self._umts = umts
        self._lte = lte
        self._nr = nr

    @classmethod
    def from_dict(cls, dikt) -> 'ListOfMeasurementsType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The listOfMeasurements-Type of this ListOfMeasurementsType.  # noqa: E501
        :rtype: ListOfMeasurementsType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def umts(self):
        """Gets the umts of this ListOfMeasurementsType.


        :return: The umts of this ListOfMeasurementsType.
        :rtype: List[str]
        """
        return self._umts

    @umts.setter
    def umts(self, umts):
        """Sets the umts of this ListOfMeasurementsType.


        :param umts: The umts of this ListOfMeasurementsType.
        :type umts: List[str]
        """
        allowed_values = ["M1", "M2", "M3", "M4", "M5", "M6_DL", "M6_UL", "M7_DL", "M7_UL"]  # noqa: E501
        if not set(umts).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `umts` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(umts) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._umts = umts

    @property
    def lte(self):
        """Gets the lte of this ListOfMeasurementsType.


        :return: The lte of this ListOfMeasurementsType.
        :rtype: List[str]
        """
        return self._lte

    @lte.setter
    def lte(self, lte):
        """Sets the lte of this ListOfMeasurementsType.


        :param lte: The lte of this ListOfMeasurementsType.
        :type lte: List[str]
        """
        allowed_values = ["M1", "M2", "M3", "M4", "M5", "M1_EVENT_TRIGGERED", "M6", "M7", "M8", "M9"]  # noqa: E501
        if not set(lte).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `lte` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(lte) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._lte = lte

    @property
    def nr(self):
        """Gets the nr of this ListOfMeasurementsType.


        :return: The nr of this ListOfMeasurementsType.
        :rtype: List[str]
        """
        return self._nr

    @nr.setter
    def nr(self, nr):
        """Sets the nr of this ListOfMeasurementsType.


        :param nr: The nr of this ListOfMeasurementsType.
        :type nr: List[str]
        """
        allowed_values = ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M1_EVENT_TRIGGERED", "M8", "M9"]  # noqa: E501
        if not set(nr).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `nr` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(nr) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._nr = nr
