# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.managed_nf_service_single_all_of_attributes import ManagedNFServiceSingleAllOfAttributes
from openapi_server import util

from openapi_server.models.managed_nf_service_single_all_of_attributes import ManagedNFServiceSingleAllOfAttributes  # noqa: E501

class ManagedNFServiceSingleAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attributes=None):  # noqa: E501
        """ManagedNFServiceSingleAllOf - a model defined in OpenAPI

        :param attributes: The attributes of this ManagedNFServiceSingleAllOf.  # noqa: E501
        :type attributes: ManagedNFServiceSingleAllOfAttributes
        """
        self.openapi_types = {
            'attributes': ManagedNFServiceSingleAllOfAttributes
        }

        self.attribute_map = {
            'attributes': 'attributes'
        }

        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'ManagedNFServiceSingleAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ManagedNFService_Single_allOf of this ManagedNFServiceSingleAllOf.  # noqa: E501
        :rtype: ManagedNFServiceSingleAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attributes(self):
        """Gets the attributes of this ManagedNFServiceSingleAllOf.


        :return: The attributes of this ManagedNFServiceSingleAllOf.
        :rtype: ManagedNFServiceSingleAllOfAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ManagedNFServiceSingleAllOf.


        :param attributes: The attributes of this ManagedNFServiceSingleAllOf.
        :type attributes: ManagedNFServiceSingleAllOfAttributes
        """

        self._attributes = attributes
