# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.serv_attr_com import ServAttrCom
from openapi_server import util

from openapi_server.models.serv_attr_com import ServAttrCom  # noqa: E501

class MaxNumberofPDUSessions(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, serv_attr_com=None, n_oof_pdu_sessions=None):  # noqa: E501
        """MaxNumberofPDUSessions - a model defined in OpenAPI

        :param serv_attr_com: The serv_attr_com of this MaxNumberofPDUSessions.  # noqa: E501
        :type serv_attr_com: ServAttrCom
        :param n_oof_pdu_sessions: The n_oof_pdu_sessions of this MaxNumberofPDUSessions.  # noqa: E501
        :type n_oof_pdu_sessions: int
        """
        self.openapi_types = {
            'serv_attr_com': ServAttrCom,
            'n_oof_pdu_sessions': int
        }

        self.attribute_map = {
            'serv_attr_com': 'servAttrCom',
            'n_oof_pdu_sessions': 'nOofPDUSessions'
        }

        self._serv_attr_com = serv_attr_com
        self._n_oof_pdu_sessions = n_oof_pdu_sessions

    @classmethod
    def from_dict(cls, dikt) -> 'MaxNumberofPDUSessions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MaxNumberofPDUSessions of this MaxNumberofPDUSessions.  # noqa: E501
        :rtype: MaxNumberofPDUSessions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def serv_attr_com(self):
        """Gets the serv_attr_com of this MaxNumberofPDUSessions.


        :return: The serv_attr_com of this MaxNumberofPDUSessions.
        :rtype: ServAttrCom
        """
        return self._serv_attr_com

    @serv_attr_com.setter
    def serv_attr_com(self, serv_attr_com):
        """Sets the serv_attr_com of this MaxNumberofPDUSessions.


        :param serv_attr_com: The serv_attr_com of this MaxNumberofPDUSessions.
        :type serv_attr_com: ServAttrCom
        """

        self._serv_attr_com = serv_attr_com

    @property
    def n_oof_pdu_sessions(self):
        """Gets the n_oof_pdu_sessions of this MaxNumberofPDUSessions.


        :return: The n_oof_pdu_sessions of this MaxNumberofPDUSessions.
        :rtype: int
        """
        return self._n_oof_pdu_sessions

    @n_oof_pdu_sessions.setter
    def n_oof_pdu_sessions(self, n_oof_pdu_sessions):
        """Sets the n_oof_pdu_sessions of this MaxNumberofPDUSessions.


        :param n_oof_pdu_sessions: The n_oof_pdu_sessions of this MaxNumberofPDUSessions.
        :type n_oof_pdu_sessions: int
        """

        self._n_oof_pdu_sessions = n_oof_pdu_sessions
