# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MeasurementPeriodLTEType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    _1024MS = "1024ms"
    _2048MS = "2048ms"
    _5120MS = "5120ms"
    _10240MS = "10240ms"
    _1MIN = "1min"
    def __init__(self):  # noqa: E501
        """MeasurementPeriodLTEType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'MeasurementPeriodLTEType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The measurementPeriodLTE-Type of this MeasurementPeriodLTEType.  # noqa: E501
        :rtype: MeasurementPeriodLTEType
        """
        return util.deserialize_model(dikt, cls)
