# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MnsAgentSingleAllOfAttributes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, system_dn=None):  # noqa: E501
        """MnsAgentSingleAllOfAttributes - a model defined in OpenAPI

        :param system_dn: The system_dn of this MnsAgentSingleAllOfAttributes.  # noqa: E501
        :type system_dn: str
        """
        self.openapi_types = {
            'system_dn': str
        }

        self.attribute_map = {
            'system_dn': 'systemDN'
        }

        self._system_dn = system_dn

    @classmethod
    def from_dict(cls, dikt) -> 'MnsAgentSingleAllOfAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MnsAgent_Single_allOf_attributes of this MnsAgentSingleAllOfAttributes.  # noqa: E501
        :rtype: MnsAgentSingleAllOfAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def system_dn(self):
        """Gets the system_dn of this MnsAgentSingleAllOfAttributes.


        :return: The system_dn of this MnsAgentSingleAllOfAttributes.
        :rtype: str
        """
        return self._system_dn

    @system_dn.setter
    def system_dn(self, system_dn):
        """Sets the system_dn of this MnsAgentSingleAllOfAttributes.


        :param system_dn: The system_dn of this MnsAgentSingleAllOfAttributes.
        :type system_dn: str
        """

        self._system_dn = system_dn
