# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.comm_model import CommModel
from openapi_server.models.plmn_id import PlmnId
from openapi_server import util

from openapi_server.models.comm_model import CommModel  # noqa: E501
from openapi_server.models.plmn_id import PlmnId  # noqa: E501

class N3iwfFunctionSingleAllOfAttributesAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, plmn_id_list=None, comm_model_list=None):  # noqa: E501
        """N3iwfFunctionSingleAllOfAttributesAllOf - a model defined in OpenAPI

        :param plmn_id_list: The plmn_id_list of this N3iwfFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :type plmn_id_list: List[PlmnId]
        :param comm_model_list: The comm_model_list of this N3iwfFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :type comm_model_list: List[CommModel]
        """
        self.openapi_types = {
            'plmn_id_list': List[PlmnId],
            'comm_model_list': List[CommModel]
        }

        self.attribute_map = {
            'plmn_id_list': 'plmnIdList',
            'comm_model_list': 'commModelList'
        }

        self._plmn_id_list = plmn_id_list
        self._comm_model_list = comm_model_list

    @classmethod
    def from_dict(cls, dikt) -> 'N3iwfFunctionSingleAllOfAttributesAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The N3iwfFunction_Single_allOf_attributes_allOf of this N3iwfFunctionSingleAllOfAttributesAllOf.  # noqa: E501
        :rtype: N3iwfFunctionSingleAllOfAttributesAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plmn_id_list(self):
        """Gets the plmn_id_list of this N3iwfFunctionSingleAllOfAttributesAllOf.


        :return: The plmn_id_list of this N3iwfFunctionSingleAllOfAttributesAllOf.
        :rtype: List[PlmnId]
        """
        return self._plmn_id_list

    @plmn_id_list.setter
    def plmn_id_list(self, plmn_id_list):
        """Sets the plmn_id_list of this N3iwfFunctionSingleAllOfAttributesAllOf.


        :param plmn_id_list: The plmn_id_list of this N3iwfFunctionSingleAllOfAttributesAllOf.
        :type plmn_id_list: List[PlmnId]
        """

        self._plmn_id_list = plmn_id_list

    @property
    def comm_model_list(self):
        """Gets the comm_model_list of this N3iwfFunctionSingleAllOfAttributesAllOf.


        :return: The comm_model_list of this N3iwfFunctionSingleAllOfAttributesAllOf.
        :rtype: List[CommModel]
        """
        return self._comm_model_list

    @comm_model_list.setter
    def comm_model_list(self, comm_model_list):
        """Sets the comm_model_list of this N3iwfFunctionSingleAllOfAttributesAllOf.


        :param comm_model_list: The comm_model_list of this N3iwfFunctionSingleAllOfAttributesAllOf.
        :type comm_model_list: List[CommModel]
        """

        self._comm_model_list = comm_model_list
