# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.managed_nf_profile import ManagedNFProfile
from openapi_server.models.pee_parameter import PeeParameter
from openapi_server.models.snssai import Snssai
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup
from openapi_server.models.tai import Tai
from openapi_server.models.tai_range import TaiRange
from openapi_server.models.vnf_parameter import VnfParameter
from openapi_server import util

from openapi_server.models.managed_nf_profile import ManagedNFProfile  # noqa: E501
from openapi_server.models.pee_parameter import PeeParameter  # noqa: E501
from openapi_server.models.snssai import Snssai  # noqa: E501
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup  # noqa: E501
from openapi_server.models.tai import Tai  # noqa: E501
from openapi_server.models.tai_range import TaiRange  # noqa: E501
from openapi_server.models.vnf_parameter import VnfParameter  # noqa: E501

class NefFunctionSingleAllOfAttributes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_label=None, vnf_parameters_list=None, pee_parameters_list=None, priority_label=None, supported_perf_metric_groups=None, supported_trace_metrics=None, s_bi_fqdn=None, snssai_list=None, managed_nf_profile=None, capability_list=None, is_capif_sup=None, tai_list=None, tai_range_list=None, dnai=None):  # noqa: E501
        """NefFunctionSingleAllOfAttributes - a model defined in OpenAPI

        :param user_label: The user_label of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type user_label: str
        :param vnf_parameters_list: The vnf_parameters_list of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type vnf_parameters_list: List[VnfParameter]
        :param pee_parameters_list: The pee_parameters_list of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type pee_parameters_list: List[PeeParameter]
        :param priority_label: The priority_label of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type priority_label: int
        :param supported_perf_metric_groups: The supported_perf_metric_groups of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        :param supported_trace_metrics: The supported_trace_metrics of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type supported_trace_metrics: List[str]
        :param s_bi_fqdn: The s_bi_fqdn of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type s_bi_fqdn: str
        :param snssai_list: The snssai_list of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type snssai_list: List[Snssai]
        :param managed_nf_profile: The managed_nf_profile of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type managed_nf_profile: ManagedNFProfile
        :param capability_list: The capability_list of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type capability_list: List[str]
        :param is_capif_sup: The is_capif_sup of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type is_capif_sup: bool
        :param tai_list: The tai_list of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type tai_list: List[Tai]
        :param tai_range_list: The tai_range_list of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type tai_range_list: List[TaiRange]
        :param dnai: The dnai of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :type dnai: str
        """
        self.openapi_types = {
            'user_label': str,
            'vnf_parameters_list': List[VnfParameter],
            'pee_parameters_list': List[PeeParameter],
            'priority_label': int,
            'supported_perf_metric_groups': List[SupportedPerfMetricGroup],
            'supported_trace_metrics': List[str],
            's_bi_fqdn': str,
            'snssai_list': List[Snssai],
            'managed_nf_profile': ManagedNFProfile,
            'capability_list': List[str],
            'is_capif_sup': bool,
            'tai_list': List[Tai],
            'tai_range_list': List[TaiRange],
            'dnai': str
        }

        self.attribute_map = {
            'user_label': 'userLabel',
            'vnf_parameters_list': 'vnfParametersList',
            'pee_parameters_list': 'peeParametersList',
            'priority_label': 'priorityLabel',
            'supported_perf_metric_groups': 'supportedPerfMetricGroups',
            'supported_trace_metrics': 'supportedTraceMetrics',
            's_bi_fqdn': 'sBIFqdn',
            'snssai_list': 'snssaiList',
            'managed_nf_profile': 'managedNFProfile',
            'capability_list': 'capabilityList',
            'is_capif_sup': 'isCAPIFSup',
            'tai_list': 'taiList',
            'tai_range_list': 'taiRangeList',
            'dnai': 'dnai'
        }

        self._user_label = user_label
        self._vnf_parameters_list = vnf_parameters_list
        self._pee_parameters_list = pee_parameters_list
        self._priority_label = priority_label
        self._supported_perf_metric_groups = supported_perf_metric_groups
        self._supported_trace_metrics = supported_trace_metrics
        self._s_bi_fqdn = s_bi_fqdn
        self._snssai_list = snssai_list
        self._managed_nf_profile = managed_nf_profile
        self._capability_list = capability_list
        self._is_capif_sup = is_capif_sup
        self._tai_list = tai_list
        self._tai_range_list = tai_range_list
        self._dnai = dnai

    @classmethod
    def from_dict(cls, dikt) -> 'NefFunctionSingleAllOfAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NefFunction_Single_allOf_attributes of this NefFunctionSingleAllOfAttributes.  # noqa: E501
        :rtype: NefFunctionSingleAllOfAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_label(self):
        """Gets the user_label of this NefFunctionSingleAllOfAttributes.


        :return: The user_label of this NefFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._user_label

    @user_label.setter
    def user_label(self, user_label):
        """Sets the user_label of this NefFunctionSingleAllOfAttributes.


        :param user_label: The user_label of this NefFunctionSingleAllOfAttributes.
        :type user_label: str
        """

        self._user_label = user_label

    @property
    def vnf_parameters_list(self):
        """Gets the vnf_parameters_list of this NefFunctionSingleAllOfAttributes.


        :return: The vnf_parameters_list of this NefFunctionSingleAllOfAttributes.
        :rtype: List[VnfParameter]
        """
        return self._vnf_parameters_list

    @vnf_parameters_list.setter
    def vnf_parameters_list(self, vnf_parameters_list):
        """Sets the vnf_parameters_list of this NefFunctionSingleAllOfAttributes.


        :param vnf_parameters_list: The vnf_parameters_list of this NefFunctionSingleAllOfAttributes.
        :type vnf_parameters_list: List[VnfParameter]
        """

        self._vnf_parameters_list = vnf_parameters_list

    @property
    def pee_parameters_list(self):
        """Gets the pee_parameters_list of this NefFunctionSingleAllOfAttributes.


        :return: The pee_parameters_list of this NefFunctionSingleAllOfAttributes.
        :rtype: List[PeeParameter]
        """
        return self._pee_parameters_list

    @pee_parameters_list.setter
    def pee_parameters_list(self, pee_parameters_list):
        """Sets the pee_parameters_list of this NefFunctionSingleAllOfAttributes.


        :param pee_parameters_list: The pee_parameters_list of this NefFunctionSingleAllOfAttributes.
        :type pee_parameters_list: List[PeeParameter]
        """

        self._pee_parameters_list = pee_parameters_list

    @property
    def priority_label(self):
        """Gets the priority_label of this NefFunctionSingleAllOfAttributes.


        :return: The priority_label of this NefFunctionSingleAllOfAttributes.
        :rtype: int
        """
        return self._priority_label

    @priority_label.setter
    def priority_label(self, priority_label):
        """Sets the priority_label of this NefFunctionSingleAllOfAttributes.


        :param priority_label: The priority_label of this NefFunctionSingleAllOfAttributes.
        :type priority_label: int
        """

        self._priority_label = priority_label

    @property
    def supported_perf_metric_groups(self):
        """Gets the supported_perf_metric_groups of this NefFunctionSingleAllOfAttributes.


        :return: The supported_perf_metric_groups of this NefFunctionSingleAllOfAttributes.
        :rtype: List[SupportedPerfMetricGroup]
        """
        return self._supported_perf_metric_groups

    @supported_perf_metric_groups.setter
    def supported_perf_metric_groups(self, supported_perf_metric_groups):
        """Sets the supported_perf_metric_groups of this NefFunctionSingleAllOfAttributes.


        :param supported_perf_metric_groups: The supported_perf_metric_groups of this NefFunctionSingleAllOfAttributes.
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        """

        self._supported_perf_metric_groups = supported_perf_metric_groups

    @property
    def supported_trace_metrics(self):
        """Gets the supported_trace_metrics of this NefFunctionSingleAllOfAttributes.


        :return: The supported_trace_metrics of this NefFunctionSingleAllOfAttributes.
        :rtype: List[str]
        """
        return self._supported_trace_metrics

    @supported_trace_metrics.setter
    def supported_trace_metrics(self, supported_trace_metrics):
        """Sets the supported_trace_metrics of this NefFunctionSingleAllOfAttributes.


        :param supported_trace_metrics: The supported_trace_metrics of this NefFunctionSingleAllOfAttributes.
        :type supported_trace_metrics: List[str]
        """

        self._supported_trace_metrics = supported_trace_metrics

    @property
    def s_bi_fqdn(self):
        """Gets the s_bi_fqdn of this NefFunctionSingleAllOfAttributes.


        :return: The s_bi_fqdn of this NefFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._s_bi_fqdn

    @s_bi_fqdn.setter
    def s_bi_fqdn(self, s_bi_fqdn):
        """Sets the s_bi_fqdn of this NefFunctionSingleAllOfAttributes.


        :param s_bi_fqdn: The s_bi_fqdn of this NefFunctionSingleAllOfAttributes.
        :type s_bi_fqdn: str
        """

        self._s_bi_fqdn = s_bi_fqdn

    @property
    def snssai_list(self):
        """Gets the snssai_list of this NefFunctionSingleAllOfAttributes.


        :return: The snssai_list of this NefFunctionSingleAllOfAttributes.
        :rtype: List[Snssai]
        """
        return self._snssai_list

    @snssai_list.setter
    def snssai_list(self, snssai_list):
        """Sets the snssai_list of this NefFunctionSingleAllOfAttributes.


        :param snssai_list: The snssai_list of this NefFunctionSingleAllOfAttributes.
        :type snssai_list: List[Snssai]
        """

        self._snssai_list = snssai_list

    @property
    def managed_nf_profile(self):
        """Gets the managed_nf_profile of this NefFunctionSingleAllOfAttributes.


        :return: The managed_nf_profile of this NefFunctionSingleAllOfAttributes.
        :rtype: ManagedNFProfile
        """
        return self._managed_nf_profile

    @managed_nf_profile.setter
    def managed_nf_profile(self, managed_nf_profile):
        """Sets the managed_nf_profile of this NefFunctionSingleAllOfAttributes.


        :param managed_nf_profile: The managed_nf_profile of this NefFunctionSingleAllOfAttributes.
        :type managed_nf_profile: ManagedNFProfile
        """

        self._managed_nf_profile = managed_nf_profile

    @property
    def capability_list(self):
        """Gets the capability_list of this NefFunctionSingleAllOfAttributes.


        :return: The capability_list of this NefFunctionSingleAllOfAttributes.
        :rtype: List[str]
        """
        return self._capability_list

    @capability_list.setter
    def capability_list(self, capability_list):
        """Sets the capability_list of this NefFunctionSingleAllOfAttributes.


        :param capability_list: The capability_list of this NefFunctionSingleAllOfAttributes.
        :type capability_list: List[str]
        """

        self._capability_list = capability_list

    @property
    def is_capif_sup(self):
        """Gets the is_capif_sup of this NefFunctionSingleAllOfAttributes.


        :return: The is_capif_sup of this NefFunctionSingleAllOfAttributes.
        :rtype: bool
        """
        return self._is_capif_sup

    @is_capif_sup.setter
    def is_capif_sup(self, is_capif_sup):
        """Sets the is_capif_sup of this NefFunctionSingleAllOfAttributes.


        :param is_capif_sup: The is_capif_sup of this NefFunctionSingleAllOfAttributes.
        :type is_capif_sup: bool
        """

        self._is_capif_sup = is_capif_sup

    @property
    def tai_list(self):
        """Gets the tai_list of this NefFunctionSingleAllOfAttributes.


        :return: The tai_list of this NefFunctionSingleAllOfAttributes.
        :rtype: List[Tai]
        """
        return self._tai_list

    @tai_list.setter
    def tai_list(self, tai_list):
        """Sets the tai_list of this NefFunctionSingleAllOfAttributes.


        :param tai_list: The tai_list of this NefFunctionSingleAllOfAttributes.
        :type tai_list: List[Tai]
        """

        self._tai_list = tai_list

    @property
    def tai_range_list(self):
        """Gets the tai_range_list of this NefFunctionSingleAllOfAttributes.


        :return: The tai_range_list of this NefFunctionSingleAllOfAttributes.
        :rtype: List[TaiRange]
        """
        return self._tai_range_list

    @tai_range_list.setter
    def tai_range_list(self, tai_range_list):
        """Sets the tai_range_list of this NefFunctionSingleAllOfAttributes.


        :param tai_range_list: The tai_range_list of this NefFunctionSingleAllOfAttributes.
        :type tai_range_list: List[TaiRange]
        """

        self._tai_range_list = tai_range_list

    @property
    def dnai(self):
        """Gets the dnai of this NefFunctionSingleAllOfAttributes.


        :return: The dnai of this NefFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._dnai

    @dnai.setter
    def dnai(self, dnai):
        """Sets the dnai of this NefFunctionSingleAllOfAttributes.


        :param dnai: The dnai of this NefFunctionSingleAllOfAttributes.
        :type dnai: str
        """

        self._dnai = dnai
