# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.comm_model import CommModel
from openapi_server.models.nf_profile import NFProfile
from openapi_server.models.pee_parameter import PeeParameter
from openapi_server.models.plmn_id import PlmnId
from openapi_server.models.snssai import Snssai
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup
from openapi_server.models.vnf_parameter import VnfParameter
from openapi_server import util

from openapi_server.models.comm_model import CommModel  # noqa: E501
from openapi_server.models.nf_profile import NFProfile  # noqa: E501
from openapi_server.models.pee_parameter import PeeParameter  # noqa: E501
from openapi_server.models.plmn_id import PlmnId  # noqa: E501
from openapi_server.models.snssai import Snssai  # noqa: E501
from openapi_server.models.supported_perf_metric_group import SupportedPerfMetricGroup  # noqa: E501
from openapi_server.models.vnf_parameter import VnfParameter  # noqa: E501

class NssfFunctionSingleAllOfAttributes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_label=None, vnf_parameters_list=None, pee_parameters_list=None, priority_label=None, supported_perf_metric_groups=None, supported_trace_metrics=None, plmn_id_list=None, s_bi_fqdn=None, c_nsiid_list=None, n_f_profile_list=None, snssai_list=None, comm_model_list=None):  # noqa: E501
        """NssfFunctionSingleAllOfAttributes - a model defined in OpenAPI

        :param user_label: The user_label of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type user_label: str
        :param vnf_parameters_list: The vnf_parameters_list of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type vnf_parameters_list: List[VnfParameter]
        :param pee_parameters_list: The pee_parameters_list of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type pee_parameters_list: List[PeeParameter]
        :param priority_label: The priority_label of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type priority_label: int
        :param supported_perf_metric_groups: The supported_perf_metric_groups of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        :param supported_trace_metrics: The supported_trace_metrics of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type supported_trace_metrics: List[str]
        :param plmn_id_list: The plmn_id_list of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type plmn_id_list: List[PlmnId]
        :param s_bi_fqdn: The s_bi_fqdn of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type s_bi_fqdn: str
        :param c_nsiid_list: The c_nsiid_list of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type c_nsiid_list: List[str]
        :param n_f_profile_list: The n_f_profile_list of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type n_f_profile_list: List[NFProfile]
        :param snssai_list: The snssai_list of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type snssai_list: List[Snssai]
        :param comm_model_list: The comm_model_list of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :type comm_model_list: List[CommModel]
        """
        self.openapi_types = {
            'user_label': str,
            'vnf_parameters_list': List[VnfParameter],
            'pee_parameters_list': List[PeeParameter],
            'priority_label': int,
            'supported_perf_metric_groups': List[SupportedPerfMetricGroup],
            'supported_trace_metrics': List[str],
            'plmn_id_list': List[PlmnId],
            's_bi_fqdn': str,
            'c_nsiid_list': List[str],
            'n_f_profile_list': List[NFProfile],
            'snssai_list': List[Snssai],
            'comm_model_list': List[CommModel]
        }

        self.attribute_map = {
            'user_label': 'userLabel',
            'vnf_parameters_list': 'vnfParametersList',
            'pee_parameters_list': 'peeParametersList',
            'priority_label': 'priorityLabel',
            'supported_perf_metric_groups': 'supportedPerfMetricGroups',
            'supported_trace_metrics': 'supportedTraceMetrics',
            'plmn_id_list': 'plmnIdList',
            's_bi_fqdn': 'sBIFqdn',
            'c_nsiid_list': 'cNSIIdList',
            'n_f_profile_list': 'nFProfileList',
            'snssai_list': 'snssaiList',
            'comm_model_list': 'commModelList'
        }

        self._user_label = user_label
        self._vnf_parameters_list = vnf_parameters_list
        self._pee_parameters_list = pee_parameters_list
        self._priority_label = priority_label
        self._supported_perf_metric_groups = supported_perf_metric_groups
        self._supported_trace_metrics = supported_trace_metrics
        self._plmn_id_list = plmn_id_list
        self._s_bi_fqdn = s_bi_fqdn
        self._c_nsiid_list = c_nsiid_list
        self._n_f_profile_list = n_f_profile_list
        self._snssai_list = snssai_list
        self._comm_model_list = comm_model_list

    @classmethod
    def from_dict(cls, dikt) -> 'NssfFunctionSingleAllOfAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NssfFunction_Single_allOf_attributes of this NssfFunctionSingleAllOfAttributes.  # noqa: E501
        :rtype: NssfFunctionSingleAllOfAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_label(self):
        """Gets the user_label of this NssfFunctionSingleAllOfAttributes.


        :return: The user_label of this NssfFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._user_label

    @user_label.setter
    def user_label(self, user_label):
        """Sets the user_label of this NssfFunctionSingleAllOfAttributes.


        :param user_label: The user_label of this NssfFunctionSingleAllOfAttributes.
        :type user_label: str
        """

        self._user_label = user_label

    @property
    def vnf_parameters_list(self):
        """Gets the vnf_parameters_list of this NssfFunctionSingleAllOfAttributes.


        :return: The vnf_parameters_list of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[VnfParameter]
        """
        return self._vnf_parameters_list

    @vnf_parameters_list.setter
    def vnf_parameters_list(self, vnf_parameters_list):
        """Sets the vnf_parameters_list of this NssfFunctionSingleAllOfAttributes.


        :param vnf_parameters_list: The vnf_parameters_list of this NssfFunctionSingleAllOfAttributes.
        :type vnf_parameters_list: List[VnfParameter]
        """

        self._vnf_parameters_list = vnf_parameters_list

    @property
    def pee_parameters_list(self):
        """Gets the pee_parameters_list of this NssfFunctionSingleAllOfAttributes.


        :return: The pee_parameters_list of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[PeeParameter]
        """
        return self._pee_parameters_list

    @pee_parameters_list.setter
    def pee_parameters_list(self, pee_parameters_list):
        """Sets the pee_parameters_list of this NssfFunctionSingleAllOfAttributes.


        :param pee_parameters_list: The pee_parameters_list of this NssfFunctionSingleAllOfAttributes.
        :type pee_parameters_list: List[PeeParameter]
        """

        self._pee_parameters_list = pee_parameters_list

    @property
    def priority_label(self):
        """Gets the priority_label of this NssfFunctionSingleAllOfAttributes.


        :return: The priority_label of this NssfFunctionSingleAllOfAttributes.
        :rtype: int
        """
        return self._priority_label

    @priority_label.setter
    def priority_label(self, priority_label):
        """Sets the priority_label of this NssfFunctionSingleAllOfAttributes.


        :param priority_label: The priority_label of this NssfFunctionSingleAllOfAttributes.
        :type priority_label: int
        """

        self._priority_label = priority_label

    @property
    def supported_perf_metric_groups(self):
        """Gets the supported_perf_metric_groups of this NssfFunctionSingleAllOfAttributes.


        :return: The supported_perf_metric_groups of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[SupportedPerfMetricGroup]
        """
        return self._supported_perf_metric_groups

    @supported_perf_metric_groups.setter
    def supported_perf_metric_groups(self, supported_perf_metric_groups):
        """Sets the supported_perf_metric_groups of this NssfFunctionSingleAllOfAttributes.


        :param supported_perf_metric_groups: The supported_perf_metric_groups of this NssfFunctionSingleAllOfAttributes.
        :type supported_perf_metric_groups: List[SupportedPerfMetricGroup]
        """

        self._supported_perf_metric_groups = supported_perf_metric_groups

    @property
    def supported_trace_metrics(self):
        """Gets the supported_trace_metrics of this NssfFunctionSingleAllOfAttributes.


        :return: The supported_trace_metrics of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[str]
        """
        return self._supported_trace_metrics

    @supported_trace_metrics.setter
    def supported_trace_metrics(self, supported_trace_metrics):
        """Sets the supported_trace_metrics of this NssfFunctionSingleAllOfAttributes.


        :param supported_trace_metrics: The supported_trace_metrics of this NssfFunctionSingleAllOfAttributes.
        :type supported_trace_metrics: List[str]
        """

        self._supported_trace_metrics = supported_trace_metrics

    @property
    def plmn_id_list(self):
        """Gets the plmn_id_list of this NssfFunctionSingleAllOfAttributes.


        :return: The plmn_id_list of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[PlmnId]
        """
        return self._plmn_id_list

    @plmn_id_list.setter
    def plmn_id_list(self, plmn_id_list):
        """Sets the plmn_id_list of this NssfFunctionSingleAllOfAttributes.


        :param plmn_id_list: The plmn_id_list of this NssfFunctionSingleAllOfAttributes.
        :type plmn_id_list: List[PlmnId]
        """

        self._plmn_id_list = plmn_id_list

    @property
    def s_bi_fqdn(self):
        """Gets the s_bi_fqdn of this NssfFunctionSingleAllOfAttributes.


        :return: The s_bi_fqdn of this NssfFunctionSingleAllOfAttributes.
        :rtype: str
        """
        return self._s_bi_fqdn

    @s_bi_fqdn.setter
    def s_bi_fqdn(self, s_bi_fqdn):
        """Sets the s_bi_fqdn of this NssfFunctionSingleAllOfAttributes.


        :param s_bi_fqdn: The s_bi_fqdn of this NssfFunctionSingleAllOfAttributes.
        :type s_bi_fqdn: str
        """

        self._s_bi_fqdn = s_bi_fqdn

    @property
    def c_nsiid_list(self):
        """Gets the c_nsiid_list of this NssfFunctionSingleAllOfAttributes.


        :return: The c_nsiid_list of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[str]
        """
        return self._c_nsiid_list

    @c_nsiid_list.setter
    def c_nsiid_list(self, c_nsiid_list):
        """Sets the c_nsiid_list of this NssfFunctionSingleAllOfAttributes.


        :param c_nsiid_list: The c_nsiid_list of this NssfFunctionSingleAllOfAttributes.
        :type c_nsiid_list: List[str]
        """

        self._c_nsiid_list = c_nsiid_list

    @property
    def n_f_profile_list(self):
        """Gets the n_f_profile_list of this NssfFunctionSingleAllOfAttributes.

        List of NF profile  # noqa: E501

        :return: The n_f_profile_list of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[NFProfile]
        """
        return self._n_f_profile_list

    @n_f_profile_list.setter
    def n_f_profile_list(self, n_f_profile_list):
        """Sets the n_f_profile_list of this NssfFunctionSingleAllOfAttributes.

        List of NF profile  # noqa: E501

        :param n_f_profile_list: The n_f_profile_list of this NssfFunctionSingleAllOfAttributes.
        :type n_f_profile_list: List[NFProfile]
        """

        self._n_f_profile_list = n_f_profile_list

    @property
    def snssai_list(self):
        """Gets the snssai_list of this NssfFunctionSingleAllOfAttributes.


        :return: The snssai_list of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[Snssai]
        """
        return self._snssai_list

    @snssai_list.setter
    def snssai_list(self, snssai_list):
        """Sets the snssai_list of this NssfFunctionSingleAllOfAttributes.


        :param snssai_list: The snssai_list of this NssfFunctionSingleAllOfAttributes.
        :type snssai_list: List[Snssai]
        """

        self._snssai_list = snssai_list

    @property
    def comm_model_list(self):
        """Gets the comm_model_list of this NssfFunctionSingleAllOfAttributes.


        :return: The comm_model_list of this NssfFunctionSingleAllOfAttributes.
        :rtype: List[CommModel]
        """
        return self._comm_model_list

    @comm_model_list.setter
    def comm_model_list(self, comm_model_list):
        """Sets the comm_model_list of this NssfFunctionSingleAllOfAttributes.


        :param comm_model_list: The comm_model_list of this NssfFunctionSingleAllOfAttributes.
        :type comm_model_list: List[CommModel]
        """

        self._comm_model_list = comm_model_list
