# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ParameterRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, max_value=None, min_value=None):  # noqa: E501
        """ParameterRange - a model defined in OpenAPI

        :param max_value: The max_value of this ParameterRange.  # noqa: E501
        :type max_value: int
        :param min_value: The min_value of this ParameterRange.  # noqa: E501
        :type min_value: int
        """
        self.openapi_types = {
            'max_value': int,
            'min_value': int
        }

        self.attribute_map = {
            'max_value': 'maxValue',
            'min_value': 'minValue'
        }

        self._max_value = max_value
        self._min_value = min_value

    @classmethod
    def from_dict(cls, dikt) -> 'ParameterRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParameterRange of this ParameterRange.  # noqa: E501
        :rtype: ParameterRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def max_value(self):
        """Gets the max_value of this ParameterRange.


        :return: The max_value of this ParameterRange.
        :rtype: int
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value):
        """Sets the max_value of this ParameterRange.


        :param max_value: The max_value of this ParameterRange.
        :type max_value: int
        """

        self._max_value = max_value

    @property
    def min_value(self):
        """Gets the min_value of this ParameterRange.


        :return: The min_value of this ParameterRange.
        :rtype: int
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value):
        """Sets the min_value of this ParameterRange.


        :param min_value: The min_value of this ParameterRange.
        :type min_value: int
        """

        self._min_value = min_value
