# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.pcf_function_single_all_of_attributes import PcfFunctionSingleAllOfAttributes
from openapi_server import util

from openapi_server.models.pcf_function_single_all_of_attributes import PcfFunctionSingleAllOfAttributes  # noqa: E501

class PcfFunctionSingleAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attributes=None):  # noqa: E501
        """PcfFunctionSingleAllOf - a model defined in OpenAPI

        :param attributes: The attributes of this PcfFunctionSingleAllOf.  # noqa: E501
        :type attributes: PcfFunctionSingleAllOfAttributes
        """
        self.openapi_types = {
            'attributes': PcfFunctionSingleAllOfAttributes
        }

        self.attribute_map = {
            'attributes': 'attributes'
        }

        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'PcfFunctionSingleAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PcfFunction_Single_allOf of this PcfFunctionSingleAllOf.  # noqa: E501
        :rtype: PcfFunctionSingleAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attributes(self):
        """Gets the attributes of this PcfFunctionSingleAllOf.


        :return: The attributes of this PcfFunctionSingleAllOf.
        :rtype: PcfFunctionSingleAllOfAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this PcfFunctionSingleAllOf.


        :param attributes: The attributes of this PcfFunctionSingleAllOf.
        :type attributes: PcfFunctionSingleAllOfAttributes
        """

        self._attributes = attributes
