# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.condition import Condition
from openapi_server.models.coverage_area_polygon_context import CoverageAreaPolygonContext
from openapi_server.models.coverage_tac_context import CoverageTACContext
from openapi_server.models.nrfq_band_context import NRFqBandContext
from openapi_server.models.object_context import ObjectContext
from openapi_server.models.plmn_context import PLMNContext
from openapi_server.models.rat_context import RATContext
from openapi_server import util

from openapi_server.models.condition import Condition  # noqa: E501
from openapi_server.models.coverage_area_polygon_context import CoverageAreaPolygonContext  # noqa: E501
from openapi_server.models.coverage_tac_context import CoverageTACContext  # noqa: E501
from openapi_server.models.nrfq_band_context import NRFqBandContext  # noqa: E501
from openapi_server.models.object_context import ObjectContext  # noqa: E501
from openapi_server.models.plmn_context import PLMNContext  # noqa: E501
from openapi_server.models.rat_context import RATContext  # noqa: E501

class RadioNetworkExpectationObjectObjectContextsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, context_attribute=None, context_condition=None, context_value_range=None):  # noqa: E501
        """RadioNetworkExpectationObjectObjectContextsInner - a model defined in OpenAPI

        :param context_attribute: The context_attribute of this RadioNetworkExpectationObjectObjectContextsInner.  # noqa: E501
        :type context_attribute: str
        :param context_condition: The context_condition of this RadioNetworkExpectationObjectObjectContextsInner.  # noqa: E501
        :type context_condition: Condition
        :param context_value_range: The context_value_range of this RadioNetworkExpectationObjectObjectContextsInner.  # noqa: E501
        :type context_value_range: List[float]
        """
        self.openapi_types = {
            'context_attribute': str,
            'context_condition': Condition,
            'context_value_range': List[float]
        }

        self.attribute_map = {
            'context_attribute': 'contextAttribute',
            'context_condition': 'contextCondition',
            'context_value_range': 'contextValueRange'
        }

        self._context_attribute = context_attribute
        self._context_condition = context_condition
        self._context_value_range = context_value_range

    @classmethod
    def from_dict(cls, dikt) -> 'RadioNetworkExpectationObjectObjectContextsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RadioNetworkExpectationObject_objectContexts_inner of this RadioNetworkExpectationObjectObjectContextsInner.  # noqa: E501
        :rtype: RadioNetworkExpectationObjectObjectContextsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context_attribute(self):
        """Gets the context_attribute of this RadioNetworkExpectationObjectObjectContextsInner.


        :return: The context_attribute of this RadioNetworkExpectationObjectObjectContextsInner.
        :rtype: str
        """
        return self._context_attribute

    @context_attribute.setter
    def context_attribute(self, context_attribute):
        """Sets the context_attribute of this RadioNetworkExpectationObjectObjectContextsInner.


        :param context_attribute: The context_attribute of this RadioNetworkExpectationObjectObjectContextsInner.
        :type context_attribute: str
        """

        self._context_attribute = context_attribute

    @property
    def context_condition(self):
        """Gets the context_condition of this RadioNetworkExpectationObjectObjectContextsInner.


        :return: The context_condition of this RadioNetworkExpectationObjectObjectContextsInner.
        :rtype: Condition
        """
        return self._context_condition

    @context_condition.setter
    def context_condition(self, context_condition):
        """Sets the context_condition of this RadioNetworkExpectationObjectObjectContextsInner.


        :param context_condition: The context_condition of this RadioNetworkExpectationObjectObjectContextsInner.
        :type context_condition: Condition
        """

        self._context_condition = context_condition

    @property
    def context_value_range(self):
        """Gets the context_value_range of this RadioNetworkExpectationObjectObjectContextsInner.


        :return: The context_value_range of this RadioNetworkExpectationObjectObjectContextsInner.
        :rtype: List[float]
        """
        return self._context_value_range

    @context_value_range.setter
    def context_value_range(self, context_value_range):
        """Sets the context_value_range of this RadioNetworkExpectationObjectObjectContextsInner.


        :param context_value_range: The context_value_range of this RadioNetworkExpectationObjectObjectContextsInner.
        :type context_value_range: List[float]
        """

        self._context_value_range = context_value_range
