# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.condition import Condition
from openapi_server.models.expectation_context import ExpectationContext
from openapi_server.models.resource_sharing_level_context import ResourceSharingLevelContext
from openapi_server.models.service_end_time_context import ServiceEndTimeContext
from openapi_server.models.service_start_time_context import ServiceStartTimeContext
from openapi_server.models.ue_mobility_level_context import UEMobilityLevelContext
from openapi_server import util

from openapi_server.models.condition import Condition  # noqa: E501
from openapi_server.models.expectation_context import ExpectationContext  # noqa: E501
from openapi_server.models.resource_sharing_level_context import ResourceSharingLevelContext  # noqa: E501
from openapi_server.models.service_end_time_context import ServiceEndTimeContext  # noqa: E501
from openapi_server.models.service_start_time_context import ServiceStartTimeContext  # noqa: E501
from openapi_server.models.ue_mobility_level_context import UEMobilityLevelContext  # noqa: E501

class ServiceSupportExpectationExpectationContextsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, context_attribute=None, context_condition=None, context_value_range=None):  # noqa: E501
        """ServiceSupportExpectationExpectationContextsInner - a model defined in OpenAPI

        :param context_attribute: The context_attribute of this ServiceSupportExpectationExpectationContextsInner.  # noqa: E501
        :type context_attribute: str
        :param context_condition: The context_condition of this ServiceSupportExpectationExpectationContextsInner.  # noqa: E501
        :type context_condition: Condition
        :param context_value_range: The context_value_range of this ServiceSupportExpectationExpectationContextsInner.  # noqa: E501
        :type context_value_range: List[float]
        """
        self.openapi_types = {
            'context_attribute': str,
            'context_condition': Condition,
            'context_value_range': List[float]
        }

        self.attribute_map = {
            'context_attribute': 'contextAttribute',
            'context_condition': 'contextCondition',
            'context_value_range': 'contextValueRange'
        }

        self._context_attribute = context_attribute
        self._context_condition = context_condition
        self._context_value_range = context_value_range

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceSupportExpectationExpectationContextsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceSupportExpectation_expectationContexts_inner of this ServiceSupportExpectationExpectationContextsInner.  # noqa: E501
        :rtype: ServiceSupportExpectationExpectationContextsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context_attribute(self):
        """Gets the context_attribute of this ServiceSupportExpectationExpectationContextsInner.


        :return: The context_attribute of this ServiceSupportExpectationExpectationContextsInner.
        :rtype: str
        """
        return self._context_attribute

    @context_attribute.setter
    def context_attribute(self, context_attribute):
        """Sets the context_attribute of this ServiceSupportExpectationExpectationContextsInner.


        :param context_attribute: The context_attribute of this ServiceSupportExpectationExpectationContextsInner.
        :type context_attribute: str
        """

        self._context_attribute = context_attribute

    @property
    def context_condition(self):
        """Gets the context_condition of this ServiceSupportExpectationExpectationContextsInner.


        :return: The context_condition of this ServiceSupportExpectationExpectationContextsInner.
        :rtype: Condition
        """
        return self._context_condition

    @context_condition.setter
    def context_condition(self, context_condition):
        """Sets the context_condition of this ServiceSupportExpectationExpectationContextsInner.


        :param context_condition: The context_condition of this ServiceSupportExpectationExpectationContextsInner.
        :type context_condition: Condition
        """

        self._context_condition = context_condition

    @property
    def context_value_range(self):
        """Gets the context_value_range of this ServiceSupportExpectationExpectationContextsInner.


        :return: The context_value_range of this ServiceSupportExpectationExpectationContextsInner.
        :rtype: List[float]
        """
        return self._context_value_range

    @context_value_range.setter
    def context_value_range(self, context_value_range):
        """Sets the context_value_range of this ServiceSupportExpectationExpectationContextsInner.


        :param context_value_range: The context_value_range of this ServiceSupportExpectationExpectationContextsInner.
        :type context_value_range: List[float]
        """

        self._context_value_range = context_value_range
