# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ServiceStartTimeContext(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, context_attribute=None, context_condition=None, context_value_range=None):  # noqa: E501
        """ServiceStartTimeContext - a model defined in OpenAPI

        :param context_attribute: The context_attribute of this ServiceStartTimeContext.  # noqa: E501
        :type context_attribute: str
        :param context_condition: The context_condition of this ServiceStartTimeContext.  # noqa: E501
        :type context_condition: str
        :param context_value_range: The context_value_range of this ServiceStartTimeContext.  # noqa: E501
        :type context_value_range: str
        """
        self.openapi_types = {
            'context_attribute': str,
            'context_condition': str,
            'context_value_range': str
        }

        self.attribute_map = {
            'context_attribute': 'contextAttribute',
            'context_condition': 'contextCondition',
            'context_value_range': 'contextValueRange'
        }

        self._context_attribute = context_attribute
        self._context_condition = context_condition
        self._context_value_range = context_value_range

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceStartTimeContext':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceStartTimeContext of this ServiceStartTimeContext.  # noqa: E501
        :rtype: ServiceStartTimeContext
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context_attribute(self):
        """Gets the context_attribute of this ServiceStartTimeContext.


        :return: The context_attribute of this ServiceStartTimeContext.
        :rtype: str
        """
        return self._context_attribute

    @context_attribute.setter
    def context_attribute(self, context_attribute):
        """Sets the context_attribute of this ServiceStartTimeContext.


        :param context_attribute: The context_attribute of this ServiceStartTimeContext.
        :type context_attribute: str
        """
        allowed_values = ["ServiceStartTime"]  # noqa: E501
        if context_attribute not in allowed_values:
            raise ValueError(
                "Invalid value for `context_attribute` ({0}), must be one of {1}"
                .format(context_attribute, allowed_values)
            )

        self._context_attribute = context_attribute

    @property
    def context_condition(self):
        """Gets the context_condition of this ServiceStartTimeContext.


        :return: The context_condition of this ServiceStartTimeContext.
        :rtype: str
        """
        return self._context_condition

    @context_condition.setter
    def context_condition(self, context_condition):
        """Sets the context_condition of this ServiceStartTimeContext.


        :param context_condition: The context_condition of this ServiceStartTimeContext.
        :type context_condition: str
        """
        allowed_values = ["IS_EQUAL_TO"]  # noqa: E501
        if context_condition not in allowed_values:
            raise ValueError(
                "Invalid value for `context_condition` ({0}), must be one of {1}"
                .format(context_condition, allowed_values)
            )

        self._context_condition = context_condition

    @property
    def context_value_range(self):
        """Gets the context_value_range of this ServiceStartTimeContext.


        :return: The context_value_range of this ServiceStartTimeContext.
        :rtype: str
        """
        return self._context_value_range

    @context_value_range.setter
    def context_value_range(self, context_value_range):
        """Sets the context_value_range of this ServiceStartTimeContext.


        :param context_value_range: The context_value_range of this ServiceStartTimeContext.
        :type context_value_range: str
        """

        self._context_value_range = context_value_range
