# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alarm_list_single import AlarmListSingle
from openapi_server.models.file_download_job_single import FileDownloadJobSingle
from openapi_server.models.files_single import FilesSingle
from openapi_server.models.management_data_collection_single import ManagementDataCollectionSingle
from openapi_server.models.management_node_single import ManagementNodeSingle
from openapi_server.models.me_context_single import MeContextSingle
from openapi_server.models.mns_agent_single import MnsAgentSingle
from openapi_server.models.mns_registry_single import MnsRegistrySingle
from openapi_server.models.ntf_subscription_control_single import NtfSubscriptionControlSingle
from openapi_server.models.perf_metric_job_single import PerfMetricJobSingle
from openapi_server.models.threshold_monitor_single import ThresholdMonitorSingle
from openapi_server.models.trace_job_single import TraceJobSingle
from openapi_server import util

from openapi_server.models.alarm_list_single import AlarmListSingle  # noqa: E501
from openapi_server.models.file_download_job_single import FileDownloadJobSingle  # noqa: E501
from openapi_server.models.files_single import FilesSingle  # noqa: E501
from openapi_server.models.management_data_collection_single import ManagementDataCollectionSingle  # noqa: E501
from openapi_server.models.management_node_single import ManagementNodeSingle  # noqa: E501
from openapi_server.models.me_context_single import MeContextSingle  # noqa: E501
from openapi_server.models.mns_agent_single import MnsAgentSingle  # noqa: E501
from openapi_server.models.mns_registry_single import MnsRegistrySingle  # noqa: E501
from openapi_server.models.ntf_subscription_control_single import NtfSubscriptionControlSingle  # noqa: E501
from openapi_server.models.perf_metric_job_single import PerfMetricJobSingle  # noqa: E501
from openapi_server.models.threshold_monitor_single import ThresholdMonitorSingle  # noqa: E501
from openapi_server.models.trace_job_single import TraceJobSingle  # noqa: E501

class SubNetworkNcO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, management_node=None, mns_agent=None, me_context=None, perf_metric_job=None, threshold_monitor=None, trace_job=None, management_data_collection=None, ntf_subscription_control=None, alarm_list=None, file_download_job=None, files=None, mns_registry=None):  # noqa: E501
        """SubNetworkNcO - a model defined in OpenAPI

        :param management_node: The management_node of this SubNetworkNcO.  # noqa: E501
        :type management_node: List[ManagementNodeSingle]
        :param mns_agent: The mns_agent of this SubNetworkNcO.  # noqa: E501
        :type mns_agent: List[MnsAgentSingle]
        :param me_context: The me_context of this SubNetworkNcO.  # noqa: E501
        :type me_context: List[MeContextSingle]
        :param perf_metric_job: The perf_metric_job of this SubNetworkNcO.  # noqa: E501
        :type perf_metric_job: List[PerfMetricJobSingle]
        :param threshold_monitor: The threshold_monitor of this SubNetworkNcO.  # noqa: E501
        :type threshold_monitor: List[ThresholdMonitorSingle]
        :param trace_job: The trace_job of this SubNetworkNcO.  # noqa: E501
        :type trace_job: List[TraceJobSingle]
        :param management_data_collection: The management_data_collection of this SubNetworkNcO.  # noqa: E501
        :type management_data_collection: List[ManagementDataCollectionSingle]
        :param ntf_subscription_control: The ntf_subscription_control of this SubNetworkNcO.  # noqa: E501
        :type ntf_subscription_control: List[NtfSubscriptionControlSingle]
        :param alarm_list: The alarm_list of this SubNetworkNcO.  # noqa: E501
        :type alarm_list: AlarmListSingle
        :param file_download_job: The file_download_job of this SubNetworkNcO.  # noqa: E501
        :type file_download_job: List[FileDownloadJobSingle]
        :param files: The files of this SubNetworkNcO.  # noqa: E501
        :type files: List[FilesSingle]
        :param mns_registry: The mns_registry of this SubNetworkNcO.  # noqa: E501
        :type mns_registry: MnsRegistrySingle
        """
        self.openapi_types = {
            'management_node': List[ManagementNodeSingle],
            'mns_agent': List[MnsAgentSingle],
            'me_context': List[MeContextSingle],
            'perf_metric_job': List[PerfMetricJobSingle],
            'threshold_monitor': List[ThresholdMonitorSingle],
            'trace_job': List[TraceJobSingle],
            'management_data_collection': List[ManagementDataCollectionSingle],
            'ntf_subscription_control': List[NtfSubscriptionControlSingle],
            'alarm_list': AlarmListSingle,
            'file_download_job': List[FileDownloadJobSingle],
            'files': List[FilesSingle],
            'mns_registry': MnsRegistrySingle
        }

        self.attribute_map = {
            'management_node': 'ManagementNode',
            'mns_agent': 'MnsAgent',
            'me_context': 'MeContext',
            'perf_metric_job': 'PerfMetricJob',
            'threshold_monitor': 'ThresholdMonitor',
            'trace_job': 'TraceJob',
            'management_data_collection': 'ManagementDataCollection',
            'ntf_subscription_control': 'NtfSubscriptionControl',
            'alarm_list': 'AlarmList',
            'file_download_job': 'FileDownloadJob',
            'files': 'Files',
            'mns_registry': 'MnsRegistry'
        }

        self._management_node = management_node
        self._mns_agent = mns_agent
        self._me_context = me_context
        self._perf_metric_job = perf_metric_job
        self._threshold_monitor = threshold_monitor
        self._trace_job = trace_job
        self._management_data_collection = management_data_collection
        self._ntf_subscription_control = ntf_subscription_control
        self._alarm_list = alarm_list
        self._file_download_job = file_download_job
        self._files = files
        self._mns_registry = mns_registry

    @classmethod
    def from_dict(cls, dikt) -> 'SubNetworkNcO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubNetwork-ncO of this SubNetworkNcO.  # noqa: E501
        :rtype: SubNetworkNcO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def management_node(self):
        """Gets the management_node of this SubNetworkNcO.


        :return: The management_node of this SubNetworkNcO.
        :rtype: List[ManagementNodeSingle]
        """
        return self._management_node

    @management_node.setter
    def management_node(self, management_node):
        """Sets the management_node of this SubNetworkNcO.


        :param management_node: The management_node of this SubNetworkNcO.
        :type management_node: List[ManagementNodeSingle]
        """

        self._management_node = management_node

    @property
    def mns_agent(self):
        """Gets the mns_agent of this SubNetworkNcO.


        :return: The mns_agent of this SubNetworkNcO.
        :rtype: List[MnsAgentSingle]
        """
        return self._mns_agent

    @mns_agent.setter
    def mns_agent(self, mns_agent):
        """Sets the mns_agent of this SubNetworkNcO.


        :param mns_agent: The mns_agent of this SubNetworkNcO.
        :type mns_agent: List[MnsAgentSingle]
        """

        self._mns_agent = mns_agent

    @property
    def me_context(self):
        """Gets the me_context of this SubNetworkNcO.


        :return: The me_context of this SubNetworkNcO.
        :rtype: List[MeContextSingle]
        """
        return self._me_context

    @me_context.setter
    def me_context(self, me_context):
        """Sets the me_context of this SubNetworkNcO.


        :param me_context: The me_context of this SubNetworkNcO.
        :type me_context: List[MeContextSingle]
        """

        self._me_context = me_context

    @property
    def perf_metric_job(self):
        """Gets the perf_metric_job of this SubNetworkNcO.


        :return: The perf_metric_job of this SubNetworkNcO.
        :rtype: List[PerfMetricJobSingle]
        """
        return self._perf_metric_job

    @perf_metric_job.setter
    def perf_metric_job(self, perf_metric_job):
        """Sets the perf_metric_job of this SubNetworkNcO.


        :param perf_metric_job: The perf_metric_job of this SubNetworkNcO.
        :type perf_metric_job: List[PerfMetricJobSingle]
        """

        self._perf_metric_job = perf_metric_job

    @property
    def threshold_monitor(self):
        """Gets the threshold_monitor of this SubNetworkNcO.


        :return: The threshold_monitor of this SubNetworkNcO.
        :rtype: List[ThresholdMonitorSingle]
        """
        return self._threshold_monitor

    @threshold_monitor.setter
    def threshold_monitor(self, threshold_monitor):
        """Sets the threshold_monitor of this SubNetworkNcO.


        :param threshold_monitor: The threshold_monitor of this SubNetworkNcO.
        :type threshold_monitor: List[ThresholdMonitorSingle]
        """

        self._threshold_monitor = threshold_monitor

    @property
    def trace_job(self):
        """Gets the trace_job of this SubNetworkNcO.


        :return: The trace_job of this SubNetworkNcO.
        :rtype: List[TraceJobSingle]
        """
        return self._trace_job

    @trace_job.setter
    def trace_job(self, trace_job):
        """Sets the trace_job of this SubNetworkNcO.


        :param trace_job: The trace_job of this SubNetworkNcO.
        :type trace_job: List[TraceJobSingle]
        """

        self._trace_job = trace_job

    @property
    def management_data_collection(self):
        """Gets the management_data_collection of this SubNetworkNcO.


        :return: The management_data_collection of this SubNetworkNcO.
        :rtype: List[ManagementDataCollectionSingle]
        """
        return self._management_data_collection

    @management_data_collection.setter
    def management_data_collection(self, management_data_collection):
        """Sets the management_data_collection of this SubNetworkNcO.


        :param management_data_collection: The management_data_collection of this SubNetworkNcO.
        :type management_data_collection: List[ManagementDataCollectionSingle]
        """

        self._management_data_collection = management_data_collection

    @property
    def ntf_subscription_control(self):
        """Gets the ntf_subscription_control of this SubNetworkNcO.


        :return: The ntf_subscription_control of this SubNetworkNcO.
        :rtype: List[NtfSubscriptionControlSingle]
        """
        return self._ntf_subscription_control

    @ntf_subscription_control.setter
    def ntf_subscription_control(self, ntf_subscription_control):
        """Sets the ntf_subscription_control of this SubNetworkNcO.


        :param ntf_subscription_control: The ntf_subscription_control of this SubNetworkNcO.
        :type ntf_subscription_control: List[NtfSubscriptionControlSingle]
        """

        self._ntf_subscription_control = ntf_subscription_control

    @property
    def alarm_list(self):
        """Gets the alarm_list of this SubNetworkNcO.


        :return: The alarm_list of this SubNetworkNcO.
        :rtype: AlarmListSingle
        """
        return self._alarm_list

    @alarm_list.setter
    def alarm_list(self, alarm_list):
        """Sets the alarm_list of this SubNetworkNcO.


        :param alarm_list: The alarm_list of this SubNetworkNcO.
        :type alarm_list: AlarmListSingle
        """

        self._alarm_list = alarm_list

    @property
    def file_download_job(self):
        """Gets the file_download_job of this SubNetworkNcO.


        :return: The file_download_job of this SubNetworkNcO.
        :rtype: List[FileDownloadJobSingle]
        """
        return self._file_download_job

    @file_download_job.setter
    def file_download_job(self, file_download_job):
        """Sets the file_download_job of this SubNetworkNcO.


        :param file_download_job: The file_download_job of this SubNetworkNcO.
        :type file_download_job: List[FileDownloadJobSingle]
        """

        self._file_download_job = file_download_job

    @property
    def files(self):
        """Gets the files of this SubNetworkNcO.


        :return: The files of this SubNetworkNcO.
        :rtype: List[FilesSingle]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this SubNetworkNcO.


        :param files: The files of this SubNetworkNcO.
        :type files: List[FilesSingle]
        """

        self._files = files

    @property
    def mns_registry(self):
        """Gets the mns_registry of this SubNetworkNcO.


        :return: The mns_registry of this SubNetworkNcO.
        :rtype: MnsRegistrySingle
        """
        return self._mns_registry

    @mns_registry.setter
    def mns_registry(self, mns_registry):
        """Sets the mns_registry of this SubNetworkNcO.


        :param mns_registry: The mns_registry of this SubNetworkNcO.
        :type mns_registry: MnsRegistrySingle
        """

        self._mns_registry = mns_registry
