# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.nrtac_range import NRTACRange
from openapi_server.models.plmn_id import PlmnId
from openapi_server import util

from openapi_server.models.nrtac_range import NRTACRange  # noqa: E501
from openapi_server.models.plmn_id import PlmnId  # noqa: E501

class TaiRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, plmn_id=None, n_rtac_rangelist=None):  # noqa: E501
        """TaiRange - a model defined in OpenAPI

        :param plmn_id: The plmn_id of this TaiRange.  # noqa: E501
        :type plmn_id: PlmnId
        :param n_rtac_rangelist: The n_rtac_rangelist of this TaiRange.  # noqa: E501
        :type n_rtac_rangelist: List[NRTACRange]
        """
        self.openapi_types = {
            'plmn_id': PlmnId,
            'n_rtac_rangelist': List[NRTACRange]
        }

        self.attribute_map = {
            'plmn_id': 'plmnId',
            'n_rtac_rangelist': 'nRTACRangelist'
        }

        self._plmn_id = plmn_id
        self._n_rtac_rangelist = n_rtac_rangelist

    @classmethod
    def from_dict(cls, dikt) -> 'TaiRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaiRange of this TaiRange.  # noqa: E501
        :rtype: TaiRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plmn_id(self):
        """Gets the plmn_id of this TaiRange.


        :return: The plmn_id of this TaiRange.
        :rtype: PlmnId
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id):
        """Sets the plmn_id of this TaiRange.


        :param plmn_id: The plmn_id of this TaiRange.
        :type plmn_id: PlmnId
        """

        self._plmn_id = plmn_id

    @property
    def n_rtac_rangelist(self):
        """Gets the n_rtac_rangelist of this TaiRange.


        :return: The n_rtac_rangelist of this TaiRange.
        :rtype: List[NRTACRange]
        """
        return self._n_rtac_rangelist

    @n_rtac_rangelist.setter
    def n_rtac_rangelist(self, n_rtac_rangelist):
        """Sets the n_rtac_rangelist of this TaiRange.


        :param n_rtac_rangelist: The n_rtac_rangelist of this TaiRange.
        :type n_rtac_rangelist: List[NRTACRange]
        """

        self._n_rtac_rangelist = n_rtac_rangelist
