# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.threshold_hysteresis import ThresholdHysteresis
from openapi_server.models.threshold_level_ind_one_of import ThresholdLevelIndOneOf
from openapi_server.models.threshold_level_ind_one_of1 import ThresholdLevelIndOneOf1
from openapi_server import util

from openapi_server.models.threshold_hysteresis import ThresholdHysteresis  # noqa: E501
from openapi_server.models.threshold_level_ind_one_of import ThresholdLevelIndOneOf  # noqa: E501
from openapi_server.models.threshold_level_ind_one_of1 import ThresholdLevelIndOneOf1  # noqa: E501

class ThresholdLevelInd(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, up=None, down=None):  # noqa: E501
        """ThresholdLevelInd - a model defined in OpenAPI

        :param up: The up of this ThresholdLevelInd.  # noqa: E501
        :type up: ThresholdHysteresis
        :param down: The down of this ThresholdLevelInd.  # noqa: E501
        :type down: ThresholdHysteresis
        """
        self.openapi_types = {
            'up': ThresholdHysteresis,
            'down': ThresholdHysteresis
        }

        self.attribute_map = {
            'up': 'up',
            'down': 'down'
        }

        self._up = up
        self._down = down

    @classmethod
    def from_dict(cls, dikt) -> 'ThresholdLevelInd':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ThresholdLevelInd of this ThresholdLevelInd.  # noqa: E501
        :rtype: ThresholdLevelInd
        """
        return util.deserialize_model(dikt, cls)

    @property
    def up(self):
        """Gets the up of this ThresholdLevelInd.


        :return: The up of this ThresholdLevelInd.
        :rtype: ThresholdHysteresis
        """
        return self._up

    @up.setter
    def up(self, up):
        """Sets the up of this ThresholdLevelInd.


        :param up: The up of this ThresholdLevelInd.
        :type up: ThresholdHysteresis
        """

        self._up = up

    @property
    def down(self):
        """Gets the down of this ThresholdLevelInd.


        :return: The down of this ThresholdLevelInd.
        :rtype: ThresholdHysteresis
        """
        return self._down

    @down.setter
    def down(self, down):
        """Sets the down of this ThresholdLevelInd.


        :param down: The down of this ThresholdLevelInd.
        :type down: ThresholdHysteresis
        """

        self._down = down
