# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UeAccProbilityDist(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, target_probability=None, numberofpreamblessent=None):  # noqa: E501
        """UeAccProbilityDist - a model defined in OpenAPI

        :param target_probability: The target_probability of this UeAccProbilityDist.  # noqa: E501
        :type target_probability: int
        :param numberofpreamblessent: The numberofpreamblessent of this UeAccProbilityDist.  # noqa: E501
        :type numberofpreamblessent: int
        """
        self.openapi_types = {
            'target_probability': int,
            'numberofpreamblessent': int
        }

        self.attribute_map = {
            'target_probability': 'targetProbability',
            'numberofpreamblessent': 'numberofpreamblessent'
        }

        self._target_probability = target_probability
        self._numberofpreamblessent = numberofpreamblessent

    @classmethod
    def from_dict(cls, dikt) -> 'UeAccProbilityDist':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UeAccProbilityDist of this UeAccProbilityDist.  # noqa: E501
        :rtype: UeAccProbilityDist
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_probability(self):
        """Gets the target_probability of this UeAccProbilityDist.


        :return: The target_probability of this UeAccProbilityDist.
        :rtype: int
        """
        return self._target_probability

    @target_probability.setter
    def target_probability(self, target_probability):
        """Sets the target_probability of this UeAccProbilityDist.


        :param target_probability: The target_probability of this UeAccProbilityDist.
        :type target_probability: int
        """

        self._target_probability = target_probability

    @property
    def numberofpreamblessent(self):
        """Gets the numberofpreamblessent of this UeAccProbilityDist.


        :return: The numberofpreamblessent of this UeAccProbilityDist.
        :rtype: int
        """
        return self._numberofpreamblessent

    @numberofpreamblessent.setter
    def numberofpreamblessent(self, numberofpreamblessent):
        """Sets the numberofpreamblessent of this UeAccProbilityDist.


        :param numberofpreamblessent: The numberofpreamblessent of this UeAccProbilityDist.
        :type numberofpreamblessent: int
        """

        self._numberofpreamblessent = numberofpreamblessent
